import { Database } from "bun:sqlite";
import { createPrivateKey, createPublicKey, sign, verify } from "node:crypto";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { parseJsonNoDuplicateKeys } from "./catfood-coe";
import { canonicalJson, sha256 } from "./catfood-harness";
import {
  CATFOOD_EVALUATION_PROVENANCE_NODES, CATFOOD_EVALUATOR_SHA256, CATFOOD_POLICY_SHA256, CatfoodTrustError, IndependentCatfoodEvaluator,
  type EvaluationResult, type ReadonlyThreadsEvidenceSource,
} from "./catfood-trust";
import { CATFOOD_THREADS_DEPENDENCY_ROOT } from "./catfood-coe";
import {
  assertCommonEnrollmentLineage, assertEnrolledRole, composeRunTrustProvenance, deriveCatfoodTrustDomain, enrolledTrustEvidence, enrollmentEvidence,
  inspectEnrolledRole, issueEnrolledActionReceipt, resolveProtectedWriterCredential, verifyEnrolledActionReceipt, verifyEnrollmentRoleEvidenceSet,
  type CatfoodEnrollmentContext,
} from "./catfood-enrollment";

export const CATFOOD_ATTESTATION_SCHEMA = "catfood-independent-attestation.v3";
export const CATFOOD_ATTESTATION_DOMAIN = "IKORABU/WP3/CATFOOD/ATTESTATION/V3";
export const CATFOOD_EVALUATION_RECEIPT_PURPOSE = "IKORABU/WP3/CATFOOD/EVALUATION-RESULT/V1";
export const CATFOOD_WRITER_CREDENTIAL_PURPOSE = "IKORABU/WP3/CATFOOD/WRITER-CREDENTIAL/V1";
export const CATFOOD_ISSUANCE_PREPARE_PURPOSE = "IKORABU/WP3/CATFOOD/ATTESTATION-ISSUANCE-PREPARE/V1";
export const CATFOOD_ISSUANCE_FINALIZE_PURPOSE = "IKORABU/WP3/CATFOOD/ATTESTATION-ISSUANCE-FINALIZE/V1";

const MAX_ARTIFACT_BYTES = 2_000_000;
const ARTIFACT_SCHEMA = "catfood-independent-attestation-artifact.v3";
const DECISION_CORE_SCHEMA = "catfood-decision-core.v1";
const EVALUATION_RECEIPT_SCHEMA = "catfood-evaluation-receipt.v1";
const WRITER_AUTHORIZATION_SCHEMA = "catfood-writer-credential-authorization.v1";
const PREPARATION_SCHEMA = "catfood-attestation-issuance-preparation.v1";
const FINALIZATION_SCHEMA = "catfood-attestation-issuance-finalization.v1";

export interface AttestationStoreConfig { writer_identity: string; signing_key_id: string; signing_public_key_pem: string }
export interface CatfoodAttestationEnrollments { source: CatfoodEnrollmentContext; custodian: CatfoodEnrollmentContext; evaluator: CatfoodEnrollmentContext; writer: CatfoodEnrollmentContext }
export interface IndependentAttestationExpected { run_id: string; bundle_sha256: string; allow_test_only?: boolean; writer_identity?: string; signing_key_id?: string; assessment_id?: string; verifier_enrollment?: CatfoodEnrollmentContext }

const SQL = `
CREATE TABLE attestation_meta(singleton INTEGER PRIMARY KEY CHECK(singleton=1),schema_version TEXT NOT NULL,writer_identity TEXT NOT NULL,signing_key_id TEXT NOT NULL,signing_public_key_pem TEXT NOT NULL,evaluator_sha256 TEXT NOT NULL,policy_sha256 TEXT NOT NULL) STRICT;
CREATE TRIGGER attestation_meta_no_update BEFORE UPDATE ON attestation_meta BEGIN SELECT RAISE(ABORT,'attestation metadata is immutable'); END;
CREATE TRIGGER attestation_meta_no_delete BEFORE DELETE ON attestation_meta BEGIN SELECT RAISE(ABORT,'attestation metadata is immutable'); END;
CREATE TABLE authenticated_assessments(assessment_id TEXT PRIMARY KEY,run_id TEXT NOT NULL,decision_core_sha256 TEXT NOT NULL,role_evidence_sha256 TEXT NOT NULL,evaluator_session_id TEXT NOT NULL,receipt_json TEXT NOT NULL CHECK(json_valid(receipt_json)),UNIQUE(run_id,decision_core_sha256,role_evidence_sha256,evaluator_session_id)) STRICT;
CREATE TRIGGER assessments_no_update BEFORE UPDATE ON authenticated_assessments BEGIN SELECT RAISE(ABORT,'assessments are create-only'); END;
CREATE TRIGGER assessments_no_delete BEFORE DELETE ON authenticated_assessments BEGIN SELECT RAISE(ABORT,'assessments are create-only'); END;
CREATE TABLE issuance_preparations(issuance_id TEXT PRIMARY KEY,assessment_id TEXT NOT NULL REFERENCES authenticated_assessments(assessment_id),writer_session_id TEXT NOT NULL,credential_sha256 TEXT NOT NULL,role_evidence_sha256 TEXT NOT NULL,credential_authorization_json TEXT NOT NULL CHECK(json_valid(credential_authorization_json)),receipt_json TEXT NOT NULL CHECK(json_valid(receipt_json)),UNIQUE(assessment_id,writer_session_id,credential_sha256,role_evidence_sha256)) STRICT;
CREATE TRIGGER preparations_no_update BEFORE UPDATE ON issuance_preparations BEGIN SELECT RAISE(ABORT,'issuance preparations are create-only'); END;
CREATE TRIGGER preparations_no_delete BEFORE DELETE ON issuance_preparations BEGIN SELECT RAISE(ABORT,'issuance preparations are create-only'); END;
CREATE TABLE issuance_finalizations(issuance_id TEXT PRIMARY KEY REFERENCES issuance_preparations(issuance_id),payload_sha256 TEXT NOT NULL,signature_sha256 TEXT NOT NULL,receipt_json TEXT NOT NULL CHECK(json_valid(receipt_json))) STRICT;
CREATE TRIGGER finalizations_no_update BEFORE UPDATE ON issuance_finalizations BEGIN SELECT RAISE(ABORT,'issuance finalizations are create-only'); END;
CREATE TRIGGER finalizations_no_delete BEFORE DELETE ON issuance_finalizations BEGIN SELECT RAISE(ABORT,'issuance finalizations are create-only'); END;
CREATE TABLE independent_attestations(attestation_id TEXT PRIMARY KEY,run_id TEXT NOT NULL,assessment_id TEXT NOT NULL REFERENCES authenticated_assessments(assessment_id),issuance_id TEXT NOT NULL UNIQUE REFERENCES issuance_finalizations(issuance_id),decision_core_sha256 TEXT NOT NULL,role_evidence_sha256 TEXT NOT NULL,scope_sha256 TEXT NOT NULL,go_sha256 TEXT NOT NULL,policy_sha256 TEXT NOT NULL,ikorabu_release_sha TEXT NOT NULL,threads_sha TEXT NOT NULL,boundary_sha256 TEXT NOT NULL,threads_release_sha256 TEXT NOT NULL,threads_schema INTEGER NOT NULL,evaluator_sha256 TEXT NOT NULL,checkpoint_id TEXT NOT NULL,evidence_coverage TEXT NOT NULL,bundle_sha256 TEXT NOT NULL,verdict TEXT NOT NULL CHECK(verdict IN('PASS','FAIL','BLOCKED')),reason_codes_json TEXT NOT NULL CHECK(json_valid(reason_codes_json)),test_only INTEGER NOT NULL CHECK(test_only IN(0,1)),writer_identity TEXT NOT NULL,signing_key_id TEXT NOT NULL,signing_key_sha256 TEXT NOT NULL,attested_at TEXT NOT NULL,payload_json TEXT NOT NULL CHECK(json_valid(payload_json)),signature_base64url TEXT NOT NULL,artifact_json TEXT NOT NULL CHECK(json_valid(artifact_json)),UNIQUE(run_id,decision_core_sha256,role_evidence_sha256,signing_key_sha256)) STRICT;
CREATE TRIGGER attestations_no_update BEFORE UPDATE ON independent_attestations BEGIN SELECT RAISE(ABORT,'attestations are create-only'); END;
CREATE TRIGGER attestations_no_delete BEFORE DELETE ON independent_attestations BEGIN SELECT RAISE(ABORT,'attestations are create-only'); END;
`;

function exact(value: Record<string, unknown>, fields: readonly string[], code = "ATTESTATION_SCHEMA_INVALID"): void { const got = Object.keys(value).sort(), want = [...fields].sort(); if (got.length !== want.length || got.some((field, index) => field !== want[index])) throw new CatfoodTrustError(code); }
function record(value: unknown, code = "ATTESTATION_SCHEMA_INVALID"): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new CatfoodTrustError(code); return value as Record<string, unknown>; }
function parseCanonical(text: string, code = "ATTESTATION_SCHEMA_INVALID"): Record<string, unknown> { let value: Record<string, unknown>; try { value = parseJsonNoDuplicateKeys(text, MAX_ARTIFACT_BYTES, 64) as Record<string, unknown>; } catch { throw new CatfoodTrustError(code); } if (canonicalJson(value) !== text) throw new CatfoodTrustError(code); return value; }
function receiptSha(value: unknown): string { return sha256(canonicalJson(value as never)); }
function roleSummary(role: Readonly<Record<string, unknown>>): Readonly<Record<string, unknown>> { return Object.freeze({ subject: role.subject, session_id: role.session_id, launch_id: record(role.launcher_observed_launch).launch_id, build_sha256: record(role.accepted_role_descriptor).artifact_root, snapshot_id: role.accepted_snapshot_id, snapshot_sha256: role.accepted_snapshot_sha256, enrollment_namespace: role.enrollment_namespace }); }
function credentialEvidence(value: Readonly<Record<string, unknown>>): Readonly<Record<string, unknown>> { return Object.freeze({ key_id: value.key_id, key_version: value.key_version, public_key_sha256: value.public_key_sha256 }); }
function assertReasons(value: unknown): readonly string[] { if (!Array.isArray(value) || value.some((item) => typeof item !== "string" || !item) || new Set(value).size !== value.length || canonicalJson(value) !== canonicalJson([...value].sort())) throw new CatfoodTrustError("ATTESTATION_RESULT_INVALID"); return value as string[]; }

export function initializeIndependentAttestationStore(path: string, config: AttestationStoreConfig): void {
  if (!existsSync(resolve(path))) throw new CatfoodTrustError("ATTESTATION_STORE_MUST_PREEXIST"); if (!/^[A-Za-z0-9][A-Za-z0-9._:-]{0,199}$/.test(config.writer_identity) || !/^[A-Za-z0-9][A-Za-z0-9._:-]{0,199}$/.test(config.signing_key_id)) throw new CatfoodTrustError("ATTESTATION_CONFIG_INVALID"); const publicKey = createPublicKey(config.signing_public_key_pem); if (publicKey.asymmetricKeyType !== "ed25519") throw new CatfoodTrustError("ATTESTATION_KEY_INVALID");
  const db = new Database(resolve(path), { strict: true, create: false }); try { if ((db.query<{ n: number }, []>("SELECT COUNT(*) n FROM sqlite_master WHERE type='table'").get()?.n ?? 0) !== 0) throw new CatfoodTrustError("ATTESTATION_STORE_NOT_EMPTY"); db.exec("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA recursive_triggers=ON;"); db.exec(SQL); db.query("INSERT INTO attestation_meta VALUES(1,?,?,?,?,?,?)").run(CATFOOD_ATTESTATION_SCHEMA, config.writer_identity, config.signing_key_id, config.signing_public_key_pem, CATFOOD_EVALUATOR_SHA256, CATFOOD_POLICY_SHA256); } finally { db.close(); }
}

function decisionCore(runId: string, bundle: Record<string, unknown>, evaluation: EvaluationResult, evaluator: Readonly<Record<string, unknown>>): Readonly<Record<string, unknown>> {
  const spec = record(bundle.spec), go = record(bundle.go), checkpoint = record(bundle.checkpoint), source = record(bundle.final_source); assertReasons(evaluation.reason_codes);
  return Object.freeze({ schema: DECISION_CORE_SCHEMA, purpose: CATFOOD_EVALUATION_RECEIPT_PURPOSE, run_id: runId, scope: Object.freeze({ environment_type: spec.environment_type, environment_instance_id: spec.environment_instance_id, organization_id: spec.organization_id, tenant_id: spec.tenant_id, account_id: spec.account_id }), spec_sha256: spec.spec_sha256, requested_window_start: spec.requested_window_start, requested_window_end: spec.requested_window_end, go_sha256: go.artifact_sha256, dependency_root: CATFOOD_THREADS_DEPENDENCY_ROOT, ikorabu_release_sha: spec.ikorabu_release_sha, threads_sha: spec.threads_sha, boundary_sha256: spec.operational_boundary_sha256, threads_release_sha256: spec.threads_release_sha256, threads_schema: spec.threads_schema, evaluator_sha256: evaluation.evaluator_sha256, policy_sha256: evaluation.policy_sha256, checkpoint_id: checkpoint.checkpoint_id, source_digest: source.digest, bundle_sha256: evaluation.rederived_bundle_sha256, verdict: evaluation.verdict, reason_codes: evaluation.reason_codes, test_only: evaluation.test_only, evidence_coverage: evaluation.evidence_coverage, evaluator: roleSummary(evaluator) });
}

function validateDecisionCore(value: unknown, expected: { run_id: string; bundle_sha256: string; trust_domain: "TEST_ONLY" | "OPERATIONAL" }): Record<string, unknown> {
  const core = record(value, "ATTESTATION_RESULT_INVALID"); exact(core, ["boundary_sha256", "bundle_sha256", "checkpoint_id", "dependency_root", "evaluator", "evaluator_sha256", "evidence_coverage", "go_sha256", "ikorabu_release_sha", "policy_sha256", "purpose", "reason_codes", "requested_window_end", "requested_window_start", "run_id", "schema", "scope", "source_digest", "spec_sha256", "test_only", "threads_release_sha256", "threads_schema", "threads_sha", "verdict"], "ATTESTATION_RESULT_INVALID"); assertReasons(core.reason_codes);
  if (core.schema !== DECISION_CORE_SCHEMA || core.purpose !== CATFOOD_EVALUATION_RECEIPT_PURPOSE || core.run_id !== expected.run_id || core.bundle_sha256 !== expected.bundle_sha256 || core.evaluator_sha256 !== CATFOOD_EVALUATOR_SHA256 || core.policy_sha256 !== CATFOOD_POLICY_SHA256 || core.dependency_root !== CATFOOD_THREADS_DEPENDENCY_ROOT || !["PASS", "FAIL", "BLOCKED"].includes(String(core.verdict)) || !["COMPLETE", "PARTIAL", "UNKNOWN"].includes(String(core.evidence_coverage)) || typeof core.test_only !== "boolean" || (expected.trust_domain === "TEST_ONLY" ? core.test_only !== true : core.test_only !== false)) throw new CatfoodTrustError("ATTESTATION_RESULT_INVALID"); for (const name of ["requested_window_start", "requested_window_end"]) if (!Number.isFinite(Date.parse(String(core[name])))) throw new CatfoodTrustError("ATTESTATION_TIME_INVALID"); return core;
}

function evaluationAction(core: Readonly<Record<string, unknown>>, roleEvidenceSha256: string): Readonly<Record<string, unknown>> { return Object.freeze({ schema: EVALUATION_RECEIPT_SCHEMA, purpose: CATFOOD_EVALUATION_RECEIPT_PURPOSE, decision_core_sha256: receiptSha(core), role_evidence_sha256: roleEvidenceSha256, evaluator: core.evaluator, run_id: core.run_id, bundle_sha256: core.bundle_sha256, source_digest: core.source_digest, policy_sha256: core.policy_sha256 }); }
function writerCredentialAction(runId: string, writer: Readonly<Record<string, unknown>>, credential: Readonly<Record<string, unknown>>, roleEvidenceSha256: string): Readonly<Record<string, unknown>> { return Object.freeze({ schema: WRITER_AUTHORIZATION_SCHEMA, purpose: CATFOOD_WRITER_CREDENTIAL_PURPOSE, run_id: runId, writer, writer_credential: credential, role_evidence_sha256: roleEvidenceSha256 }); }
function preparationAction(assessmentId: string, evaluationReceiptSha256: string, decisionCoreSha256: string, writer: Readonly<Record<string, unknown>>, credential: Readonly<Record<string, unknown>>, credentialAuthorizationSha256: string, roleEvidenceSha256: string): Readonly<Record<string, unknown>> { return Object.freeze({ schema: PREPARATION_SCHEMA, purpose: CATFOOD_ISSUANCE_PREPARE_PURPOSE, assessment_id: assessmentId, evaluation_receipt_sha256: evaluationReceiptSha256, decision_core_sha256: decisionCoreSha256, writer, writer_credential: credential, credential_authorization_sha256: credentialAuthorizationSha256, role_evidence_sha256: roleEvidenceSha256, payload_domain: CATFOOD_ATTESTATION_DOMAIN }); }
function finalizationAction(payload: Record<string, unknown>, payloadText: string, signatureBase64url: string): Readonly<Record<string, unknown>> { return Object.freeze({ schema: FINALIZATION_SCHEMA, purpose: CATFOOD_ISSUANCE_FINALIZE_PURPOSE, issuance_id: payload.issuance_id, assessment_id: payload.assessment_id, payload_sha256: sha256(payloadText), signature_sha256: sha256(Buffer.from(signatureBase64url, "base64url")), evaluation_receipt_sha256: payload.evaluation_receipt_sha256, credential_authorization_sha256: payload.credential_authorization_sha256, preparation_receipt_sha256: payload.issuance_preparation_sha256, role_evidence_sha256: payload.role_evidence_sha256, writer_credential: payload.writer_credential }); }

export class IndependentCatfoodAttestationWriter {
  private readonly db: Database; private readonly evaluator: IndependentCatfoodEvaluator; private readonly privateKey: ReturnType<typeof createPrivateKey>; private readonly meta: Record<string, unknown>; private readonly enrollment: Record<string, unknown>; private readonly roles: Readonly<CatfoodAttestationEnrollments>;
  constructor(controlPath: string, checkpointPath: string, attestationPath: string, source: ReadonlyThreadsEvidenceSource, privateKeyPem: string, enrollment?: Readonly<CatfoodAttestationEnrollments>) {
    if ([resolve(controlPath), resolve(checkpointPath)].includes(resolve(attestationPath))) throw new CatfoodTrustError("ATTESTATION_STORE_MUST_BE_SEPARATE"); if (!enrollment) throw new CatfoodTrustError("ATTESTATION_ENROLLMENT_REQUIRED"); this.db = new Database(resolve(attestationPath), { strict: true, create: false });
    try {
      this.db.exec("PRAGMA recursive_triggers=ON; PRAGMA synchronous=FULL;"); this.meta = this.db.query<Record<string, unknown>, []>("SELECT * FROM attestation_meta WHERE singleton=1").get() ?? {}; const required = ["attestation_meta", "attestation_meta_no_update", "attestation_meta_no_delete", "authenticated_assessments", "assessments_no_update", "assessments_no_delete", "issuance_preparations", "preparations_no_update", "preparations_no_delete", "issuance_finalizations", "finalizations_no_update", "finalizations_no_delete", "independent_attestations", "attestations_no_update", "attestations_no_delete"]; const present = new Set(this.db.query<{ name: string }, []>("SELECT name FROM sqlite_master WHERE name NOT LIKE 'sqlite_%'").all().map((row) => row.name)); const recursive = Number(Object.values(this.db.query<Record<string, unknown>, []>("PRAGMA recursive_triggers").get() ?? {})[0]); if (required.some((name) => !present.has(name)) || recursive !== 1 || this.meta.schema_version !== CATFOOD_ATTESTATION_SCHEMA || this.meta.evaluator_sha256 !== CATFOOD_EVALUATOR_SHA256 || this.meta.policy_sha256 !== CATFOOD_POLICY_SHA256) throw new CatfoodTrustError("ATTESTATION_STORE_UNHEALTHY");
      this.privateKey = createPrivateKey(privateKeyPem); if (this.privateKey.asymmetricKeyType !== "ed25519") throw new CatfoodTrustError("ATTESTATION_KEY_INVALID"); const actual = createPublicKey(this.privateKey).export({ type: "spki", format: "der" }), pinned = createPublicKey(String(this.meta.signing_public_key_pem)).export({ type: "spki", format: "der" }); if (!actual.equals(pinned)) throw new CatfoodTrustError("ATTESTATION_SIGNING_KEY_MISMATCH"); const protectedCredential = resolveProtectedWriterCredential(enrollment.writer); if (protectedCredential.key_id !== this.meta.signing_key_id || !actual.equals(createPublicKey(String(protectedCredential.public_key_pem)).export({ type: "spki", format: "der" }))) throw new CatfoodTrustError("ATTESTATION_WRITER_CREDENTIAL_INVALID");
      const domain = source.mode === "OPERATIONAL" ? "OPERATIONAL" : "TEST_ONLY"; assertEnrolledRole(enrollment.source, "source", domain); assertEnrolledRole(enrollment.custodian, "custodian", domain); assertEnrolledRole(enrollment.evaluator, "evaluator", domain); assertEnrolledRole(enrollment.writer, "writer", domain); const common = assertCommonEnrollmentLineage([enrollment.source, enrollment.custodian, enrollment.evaluator, enrollment.writer]); this.enrollment = { authority_anchor: common.authority_anchor, accepted_snapshot_id: common.accepted_snapshot_id, accepted_snapshot_sha256: common.accepted_snapshot_sha256, enrollment_namespace: common.enrollment_namespace, build_policy_sha256: common.build_policy_sha256, roles: [enrollment.source, enrollment.custodian, enrollment.evaluator, enrollment.writer].map(enrollmentEvidence) }; this.roles = enrollment; this.evaluator = new IndependentCatfoodEvaluator(controlPath, checkpointPath, source, enrollment.evaluator);
    } catch (error) { this.db.close(); throw error; }
  }
  close(): void { this.evaluator.close(); this.db.close(); }

  attest(runId: string, attestedAt?: string): string {
    const bundle = this.evaluator.rederive(runId), provenance = composeRunTrustProvenance([this.roles.source, this.roles.custodian, this.roles.evaluator, this.roles.writer], bundle), evaluation = this.evaluator.evaluate(runId, provenance); if (evaluation.rederived_bundle_sha256 !== sha256(canonicalJson(bundle))) throw new CatfoodTrustError("EVALUATOR_OUTPUT_MISMATCH"); const trustDomain = evaluation.test_only ? "TEST_ONLY" : "OPERATIONAL", roles = verifyEnrollmentRoleEvidenceSet(this.enrollment.roles, this.roles.writer, trustDomain, runId), evaluatorRole = roles.find((role) => role.role === "evaluator")!, writerRole = roles.find((role) => role.role === "writer")!, roleEvidenceSha256 = receiptSha(roles), enrollment = { ...this.enrollment, roles, provenance: enrolledTrustEvidence(provenance) }, core = decisionCore(runId, bundle, evaluation, evaluatorRole), coreSha = receiptSha(core), protectedCredential = resolveProtectedWriterCredential(this.roles.writer), credential = credentialEvidence(protectedCredential);
    const completed = this.db.query<{ attestation_id: string; attested_at: string }, [string, string, string, string]>("SELECT attestation_id,attested_at FROM independent_attestations WHERE run_id=? AND decision_core_sha256=? AND role_evidence_sha256=? AND signing_key_sha256=?").get(runId, coreSha, roleEvidenceSha256, String(credential.public_key_sha256)); if (completed) { if (attestedAt !== undefined && attestedAt !== completed.attested_at) throw new CatfoodTrustError("ATTESTATION_TIME_INVALID"); return completed.attestation_id; }
    const evaluatorSession = String(evaluatorRole.session_id); let evaluationReceipt: Record<string, unknown>; const storedAssessment = this.db.query<{ receipt_json: string }, [string, string, string, string]>("SELECT receipt_json FROM authenticated_assessments WHERE run_id=? AND decision_core_sha256=? AND role_evidence_sha256=? AND evaluator_session_id=?").get(runId, coreSha, roleEvidenceSha256, evaluatorSession);
    if (storedAssessment) evaluationReceipt = parseCanonical(storedAssessment.receipt_json, "ATTESTATION_RESULT_RECEIPT_INVALID"); else { const action = evaluationAction(core, roleEvidenceSha256), authorityReceipt = issueEnrolledActionReceipt(this.roles.evaluator, "evaluator", "evaluator.result.commit", action, "INDEPENDENT_EVALUATION"), observed = verifyEnrolledActionReceipt(authorityReceipt, this.roles.writer, { role: "evaluator", action: "evaluator.result.commit", purpose_class: "INDEPENDENT_EVALUATION", scope: runId, action_payload: action, role_evidence: evaluatorRole }); evaluationReceipt = { schema: EVALUATION_RECEIPT_SCHEMA, purpose: CATFOOD_EVALUATION_RECEIPT_PURPOSE, assessment_id: observed.action_id, decision_core: core, decision_core_sha256: coreSha, role_evidence_sha256: roleEvidenceSha256, evaluator: roleSummary(evaluatorRole), action_receipt: authorityReceipt }; this.db.query("INSERT INTO authenticated_assessments VALUES(?,?,?,?,?,?)").run(evaluationReceipt.assessment_id, runId, coreSha, roleEvidenceSha256, evaluatorSession, canonicalJson(evaluationReceipt as never)); }
    const assessmentId = String(evaluationReceipt.assessment_id), evaluationReceiptSha = receiptSha(evaluationReceipt), writer = roleSummary(writerRole), credentialSha = receiptSha(credential); let credentialAuthorization: Record<string, unknown>, issuancePreparation: Record<string, unknown>; const storedPreparation = this.db.query<{ credential_authorization_json: string; receipt_json: string }, [string, string, string, string]>("SELECT credential_authorization_json,receipt_json FROM issuance_preparations WHERE assessment_id=? AND writer_session_id=? AND credential_sha256=? AND role_evidence_sha256=?").get(assessmentId, String(writerRole.session_id), credentialSha, roleEvidenceSha256);
    if (storedPreparation) { credentialAuthorization = parseCanonical(storedPreparation.credential_authorization_json, "ATTESTATION_WRITER_CREDENTIAL_INVALID"); issuancePreparation = parseCanonical(storedPreparation.receipt_json, "ATTESTATION_ISSUANCE_INVALID"); } else { const credentialAction = writerCredentialAction(runId, writer, credential, roleEvidenceSha256), credentialReceipt = issueEnrolledActionReceipt(this.roles.writer, "writer", "writer.credential.authorize", credentialAction, "ATTESTATION"); verifyEnrolledActionReceipt(credentialReceipt, this.roles.writer, { role: "writer", action: "writer.credential.authorize", purpose_class: "ATTESTATION", scope: runId, action_payload: credentialAction, role_evidence: writerRole }); credentialAuthorization = { schema: WRITER_AUTHORIZATION_SCHEMA, purpose: CATFOOD_WRITER_CREDENTIAL_PURPOSE, writer_credential: credential, action_receipt: credentialReceipt }; const prepareAction = preparationAction(assessmentId, evaluationReceiptSha, coreSha, writer, credential, receiptSha(credentialAuthorization), roleEvidenceSha256), preparationReceipt = issueEnrolledActionReceipt(this.roles.writer, "writer", "writer.issuance.prepare", prepareAction, "ATTESTATION"), prepared = verifyEnrolledActionReceipt(preparationReceipt, this.roles.writer, { role: "writer", action: "writer.issuance.prepare", purpose_class: "ATTESTATION", scope: runId, action_payload: prepareAction, role_evidence: writerRole }); issuancePreparation = { schema: PREPARATION_SCHEMA, purpose: CATFOOD_ISSUANCE_PREPARE_PURPOSE, issuance_id: prepared.action_id, attested_at: prepared.observed_at, valid_until: prepared.valid_until, action_receipt: preparationReceipt }; this.db.query("INSERT INTO issuance_preparations VALUES(?,?,?,?,?,?,?)").run(issuancePreparation.issuance_id, assessmentId, writerRole.session_id, credentialSha, roleEvidenceSha256, canonicalJson(credentialAuthorization as never), canonicalJson(issuancePreparation as never)); }
    if (attestedAt !== undefined && attestedAt !== issuancePreparation.attested_at) throw new CatfoodTrustError("ATTESTATION_TIME_INVALID"); const payload = { domain: CATFOOD_ATTESTATION_DOMAIN, schema: CATFOOD_ATTESTATION_SCHEMA, purpose: CATFOOD_ISSUANCE_FINALIZE_PURPOSE, trust_domain: trustDomain, decision_core: core, assessment_id: assessmentId, evaluation_receipt_sha256: evaluationReceiptSha, enrollment, role_evidence_sha256: roleEvidenceSha256, evaluation_role_evidence_sha256: roleEvidenceSha256, evaluator: roleSummary(evaluatorRole), writer, writer_identity: this.meta.writer_identity, signing_key_id: this.meta.signing_key_id, writer_credential: credential, credential_authorization_sha256: receiptSha(credentialAuthorization), issuance_id: issuancePreparation.issuance_id, issuance_preparation_sha256: receiptSha(issuancePreparation), attested_at: issuancePreparation.attested_at }, payloadText = canonicalJson(payload as never), signature = sign(null, Buffer.from(`${CATFOOD_ATTESTATION_DOMAIN}\n${payloadText}`), this.privateKey).toString("base64url"), finalizeAction = finalizationAction(payload, payloadText, signature);
    let issuanceReceipt: Record<string, unknown>; const storedFinalization = this.db.query<{ payload_sha256: string; signature_sha256: string; receipt_json: string }, [string]>("SELECT payload_sha256,signature_sha256,receipt_json FROM issuance_finalizations WHERE issuance_id=?").get(String(payload.issuance_id)); if (storedFinalization) { if (storedFinalization.payload_sha256 !== finalizeAction.payload_sha256 || storedFinalization.signature_sha256 !== finalizeAction.signature_sha256) throw new CatfoodTrustError("ATTESTATION_ISSUANCE_CONFLICT"); issuanceReceipt = parseCanonical(storedFinalization.receipt_json, "ATTESTATION_ISSUANCE_INVALID"); } else { const finalReceipt = issueEnrolledActionReceipt(this.roles.writer, "writer", "writer.issuance.finalize", finalizeAction, "ATTESTATION", { payload_json: payloadText, signature_base64url: signature }, true), finalized = verifyEnrolledActionReceipt(finalReceipt, this.roles.writer, { role: "writer", action: "writer.issuance.finalize", purpose_class: "ATTESTATION", scope: runId, action_payload: finalizeAction, role_evidence: writerRole }); issuanceReceipt = { schema: FINALIZATION_SCHEMA, purpose: CATFOOD_ISSUANCE_FINALIZE_PURPOSE, issuance_id: finalized.action_id, finalized_at: finalized.observed_at, action_receipt: finalReceipt }; this.db.query("INSERT INTO issuance_finalizations VALUES(?,?,?,?)").run(payload.issuance_id, finalizeAction.payload_sha256, finalizeAction.signature_sha256, canonicalJson(issuanceReceipt as never)); }
    const artifact = { schema: ARTIFACT_SCHEMA, payload_json: payloadText, signature_base64url: signature, evaluation_receipt: evaluationReceipt, writer_credential_authorization: credentialAuthorization, issuance_preparation: issuancePreparation, issuance_receipt: issuanceReceipt }, artifactText = canonicalJson(artifact as never), id = `att:${sha256(artifactText).slice(0, 32)}`, spec = record(bundle.spec), go = record(bundle.go), checkpoint = record(bundle.checkpoint); this.db.query("INSERT INTO independent_attestations(attestation_id,run_id,assessment_id,issuance_id,decision_core_sha256,role_evidence_sha256,scope_sha256,go_sha256,policy_sha256,ikorabu_release_sha,threads_sha,boundary_sha256,threads_release_sha256,threads_schema,evaluator_sha256,checkpoint_id,evidence_coverage,bundle_sha256,verdict,reason_codes_json,test_only,writer_identity,signing_key_id,signing_key_sha256,attested_at,payload_json,signature_base64url,artifact_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id, runId, assessmentId, payload.issuance_id, coreSha, roleEvidenceSha256, sha256(canonicalJson(core.scope as never)), go.artifact_sha256, evaluation.policy_sha256, spec.ikorabu_release_sha, spec.threads_sha, spec.operational_boundary_sha256, spec.threads_release_sha256, spec.threads_schema, evaluation.evaluator_sha256, checkpoint.checkpoint_id, evaluation.evidence_coverage, evaluation.rederived_bundle_sha256, evaluation.verdict, canonicalJson(evaluation.reason_codes as never), evaluation.test_only ? 1 : 0, payload.writer_identity, payload.signing_key_id, credential.public_key_sha256, payload.attested_at, payloadText, signature, artifactText); return id;
  }
}

export function verifyAttestationRoleEvidence(payload: Record<string, unknown>, verifierEnrollment: CatfoodEnrollmentContext, trustDomain: "TEST_ONLY" | "OPERATIONAL"): readonly Readonly<Record<string, unknown>>[] {
  const verifier = assertEnrolledRole(verifierEnrollment, "verifier", trustDomain), enrollment = record(payload.enrollment, "ATTESTATION_ENROLLMENT_MISMATCH"), provenance = enrollment.provenance as import("./catfood-enrollment").VerifiedTrustProvenance | undefined; if (verifier.authority_anchor !== enrollment.authority_anchor || verifier.accepted_snapshot_id !== enrollment.accepted_snapshot_id || verifier.accepted_snapshot_sha256 !== enrollment.accepted_snapshot_sha256 || verifier.enrollment_namespace !== enrollment.enrollment_namespace || verifier.build_policy_sha256 !== enrollment.build_policy_sha256 || !provenance || deriveCatfoodTrustDomain(provenance, CATFOOD_EVALUATION_PROVENANCE_NODES) !== trustDomain) throw new CatfoodTrustError("ATTESTATION_ENROLLMENT_MISMATCH"); const roles = verifyEnrollmentRoleEvidenceSet(enrollment.roles, verifierEnrollment, trustDomain, String(record(payload.decision_core).run_id)); if (payload.role_evidence_sha256 !== receiptSha(roles) || payload.evaluation_role_evidence_sha256 !== receiptSha(roles)) throw new CatfoodTrustError("ATTESTATION_ROLE_EVIDENCE_INVALID"); return roles;
}

export function verifyIndependentAttestationArtifact(artifactJson: string, expected: IndependentAttestationExpected, trustDomain: "TEST_ONLY" | "OPERATIONAL" = "TEST_ONLY"): EvaluationResult["verdict"] {
  if (!expected.verifier_enrollment) throw new CatfoodTrustError("ATTESTATION_VERIFIER_ENROLLMENT_REQUIRED"); inspectEnrolledRole(expected.verifier_enrollment, "verifier", trustDomain === "TEST_ONLY" ? "verifier.accept.release" : "verifier.operational.release", expected.run_id, "ATTESTATION"); const artifact = parseCanonical(artifactJson); exact(artifact, ["evaluation_receipt", "issuance_preparation", "issuance_receipt", "payload_json", "schema", "signature_base64url", "writer_credential_authorization"]); if (artifact.schema !== ARTIFACT_SCHEMA || typeof artifact.payload_json !== "string" || typeof artifact.signature_base64url !== "string") throw new CatfoodTrustError("ATTESTATION_SCHEMA_INVALID");
  const payload = parseCanonical(artifact.payload_json), expectedPayloadFields = ["assessment_id", "attested_at", "credential_authorization_sha256", "decision_core", "domain", "enrollment", "evaluation_receipt_sha256", "evaluation_role_evidence_sha256", "evaluator", "issuance_id", "issuance_preparation_sha256", "purpose", "role_evidence_sha256", "schema", "signing_key_id", "trust_domain", "writer", "writer_credential", "writer_identity"]; exact(payload, expectedPayloadFields); if (payload.domain !== CATFOOD_ATTESTATION_DOMAIN || payload.schema !== CATFOOD_ATTESTATION_SCHEMA || payload.purpose !== CATFOOD_ISSUANCE_FINALIZE_PURPOSE || payload.trust_domain !== trustDomain || trustDomain === "TEST_ONLY" && expected.allow_test_only !== true) throw new CatfoodTrustError("ATTESTATION_INVALID"); const core = validateDecisionCore(payload.decision_core, { run_id: expected.run_id, bundle_sha256: expected.bundle_sha256, trust_domain: trustDomain }), roles = verifyAttestationRoleEvidence(payload, expected.verifier_enrollment, trustDomain), evaluatorRole = roles.find((role) => role.role === "evaluator")!, writerRole = roles.find((role) => role.role === "writer")!, evaluator = roleSummary(evaluatorRole), writer = roleSummary(writerRole); if (canonicalJson(payload.evaluator as never) !== canonicalJson(evaluator as never) || canonicalJson(payload.writer as never) !== canonicalJson(writer as never) || canonicalJson(core.evaluator as never) !== canonicalJson(evaluator as never)) throw new CatfoodTrustError("ATTESTATION_ASSOCIATION_INVALID");
  const protectedCredential = resolveProtectedWriterCredential(expected.verifier_enrollment, record(payload.writer_credential, "ATTESTATION_WRITER_CREDENTIAL_INVALID")), credential = credentialEvidence(protectedCredential); if (canonicalJson(payload.writer_credential as never) !== canonicalJson(credential as never) || payload.signing_key_id !== credential.key_id || expected.signing_key_id && payload.signing_key_id !== expected.signing_key_id || expected.writer_identity && payload.writer_identity !== expected.writer_identity) throw new CatfoodTrustError("ATTESTATION_WRITER_CREDENTIAL_INVALID"); if (!verify(null, Buffer.from(`${CATFOOD_ATTESTATION_DOMAIN}\n${artifact.payload_json}`), createPublicKey(String(protectedCredential.public_key_pem)), Buffer.from(artifact.signature_base64url, "base64url"))) throw new CatfoodTrustError("ATTESTATION_SIGNATURE_INVALID");
  const roleEvidenceSha = receiptSha(roles), evaluationReceipt = record(artifact.evaluation_receipt, "ATTESTATION_RESULT_RECEIPT_INVALID"); exact(evaluationReceipt, ["action_receipt", "assessment_id", "decision_core", "decision_core_sha256", "evaluator", "purpose", "role_evidence_sha256", "schema"], "ATTESTATION_RESULT_RECEIPT_INVALID"); if (evaluationReceipt.schema !== EVALUATION_RECEIPT_SCHEMA || evaluationReceipt.purpose !== CATFOOD_EVALUATION_RECEIPT_PURPOSE || evaluationReceipt.decision_core_sha256 !== receiptSha(core) || canonicalJson(evaluationReceipt.decision_core as never) !== canonicalJson(core as never) || evaluationReceipt.role_evidence_sha256 !== roleEvidenceSha || canonicalJson(evaluationReceipt.evaluator as never) !== canonicalJson(evaluator as never) || payload.assessment_id !== evaluationReceipt.assessment_id || payload.evaluation_receipt_sha256 !== receiptSha(evaluationReceipt) || expected.assessment_id && expected.assessment_id !== evaluationReceipt.assessment_id) throw new CatfoodTrustError("ATTESTATION_RESULT_RECEIPT_INVALID"); const evaluationActionPayload = evaluationAction(core, roleEvidenceSha), evaluationObservation = verifyEnrolledActionReceipt(evaluationReceipt.action_receipt, expected.verifier_enrollment, { role: "evaluator", action: "evaluator.result.commit", purpose_class: "INDEPENDENT_EVALUATION", scope: expected.run_id, action_payload: evaluationActionPayload, role_evidence: evaluatorRole }); if (evaluationObservation.action_id !== evaluationReceipt.assessment_id) throw new CatfoodTrustError("ATTESTATION_RESULT_RECEIPT_INVALID");
  const authorization = record(artifact.writer_credential_authorization, "ATTESTATION_WRITER_CREDENTIAL_INVALID"); exact(authorization, ["action_receipt", "purpose", "schema", "writer_credential"], "ATTESTATION_WRITER_CREDENTIAL_INVALID"); if (authorization.schema !== WRITER_AUTHORIZATION_SCHEMA || authorization.purpose !== CATFOOD_WRITER_CREDENTIAL_PURPOSE || canonicalJson(authorization.writer_credential as never) !== canonicalJson(credential as never) || payload.credential_authorization_sha256 !== receiptSha(authorization)) throw new CatfoodTrustError("ATTESTATION_WRITER_CREDENTIAL_INVALID"); const credentialActionPayload = writerCredentialAction(expected.run_id, writer, credential, roleEvidenceSha), credentialObservation = verifyEnrolledActionReceipt(authorization.action_receipt, expected.verifier_enrollment, { role: "writer", action: "writer.credential.authorize", purpose_class: "ATTESTATION", scope: expected.run_id, action_payload: credentialActionPayload, role_evidence: writerRole });
  const preparation = record(artifact.issuance_preparation, "ATTESTATION_ISSUANCE_INVALID"); exact(preparation, ["action_receipt", "attested_at", "issuance_id", "purpose", "schema", "valid_until"], "ATTESTATION_ISSUANCE_INVALID"); if (preparation.schema !== PREPARATION_SCHEMA || preparation.purpose !== CATFOOD_ISSUANCE_PREPARE_PURPOSE || payload.issuance_id !== preparation.issuance_id || payload.issuance_preparation_sha256 !== receiptSha(preparation) || payload.attested_at !== preparation.attested_at) throw new CatfoodTrustError("ATTESTATION_ISSUANCE_INVALID"); const prepareActionPayload = preparationAction(String(payload.assessment_id), String(payload.evaluation_receipt_sha256), receiptSha(core), writer, credential, receiptSha(authorization), roleEvidenceSha), prepared = verifyEnrolledActionReceipt(preparation.action_receipt, expected.verifier_enrollment, { role: "writer", action: "writer.issuance.prepare", purpose_class: "ATTESTATION", scope: expected.run_id, action_payload: prepareActionPayload, role_evidence: writerRole }); if (prepared.action_id !== preparation.issuance_id || prepared.observed_at !== preparation.attested_at || prepared.valid_until !== preparation.valid_until) throw new CatfoodTrustError("ATTESTATION_ISSUANCE_INVALID");
  const issuance = record(artifact.issuance_receipt, "ATTESTATION_ISSUANCE_INVALID"); exact(issuance, ["action_receipt", "finalized_at", "issuance_id", "purpose", "schema"], "ATTESTATION_ISSUANCE_INVALID"); const finalizeActionPayload = finalizationAction(payload, artifact.payload_json, artifact.signature_base64url); if (issuance.schema !== FINALIZATION_SCHEMA || issuance.purpose !== CATFOOD_ISSUANCE_FINALIZE_PURPOSE || issuance.issuance_id !== payload.issuance_id) throw new CatfoodTrustError("ATTESTATION_ISSUANCE_INVALID"); const finalized = verifyEnrolledActionReceipt(issuance.action_receipt, expected.verifier_enrollment, { role: "writer", action: "writer.issuance.finalize", purpose_class: "ATTESTATION", scope: expected.run_id, action_payload: finalizeActionPayload, role_evidence: writerRole }); if (finalized.action_id !== issuance.issuance_id || finalized.observed_at !== issuance.finalized_at) throw new CatfoodTrustError("ATTESTATION_ISSUANCE_INVALID");
  const evaluationAt = Date.parse(String(evaluationObservation.observed_at)), windowEnd = Date.parse(String(core.requested_window_end)), credentialAt = Date.parse(String(credentialObservation.observed_at)), preparedAt = Date.parse(String(prepared.observed_at)), finalizedAt = Date.parse(String(finalized.observed_at)), validUntil = Date.parse(String(prepared.valid_until)); if (![evaluationAt, windowEnd, credentialAt, preparedAt, finalizedAt, validUntil].every(Number.isFinite) || evaluationAt < windowEnd || credentialAt > preparedAt || evaluationAt > preparedAt || preparedAt > finalizedAt || finalizedAt > validUntil) throw new CatfoodTrustError("ATTESTATION_TIME_INVALID"); return core.verdict as EvaluationResult["verdict"];
}

export function verifyIndependentAttestation(artifactJson: string, expected: IndependentAttestationExpected): EvaluationResult["verdict"];
export function verifyIndependentAttestation(payloadJson: string, signatureBase64url: string, publicKeyPem: string, expected: IndependentAttestationExpected): EvaluationResult["verdict"];
export function verifyIndependentAttestation(artifactOrPayload: string, expectedOrSignature: IndependentAttestationExpected | string, _legacyPublicKey?: string, _legacyExpected?: IndependentAttestationExpected): EvaluationResult["verdict"] { if (typeof expectedOrSignature === "string") throw new CatfoodTrustError("ATTESTATION_VERSION_UNSUPPORTED"); return verifyIndependentAttestationArtifact(artifactOrPayload, expectedOrSignature, "TEST_ONLY"); }
