import { Database } from "bun:sqlite";
import { describe, expect, test } from "bun:test";
import { createHash, generateKeyPairSync, sign, type KeyObject } from "node:crypto";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { canonicalJson } from "../web/lib/catfood-harness";
import { collectCurrentRuntimeSubject, observeTestOnlyRoleLaunch, roleChannelAcceptedSnapshotDigest, roleChannelArtifactDescriptor, type CatfoodActionPurpose, type CatfoodEnrollmentRole, type TestEnrollmentBinding } from "../web/lib/catfood-enrollment";
import { CATFOOD_POLICY_SHA256, CatfoodTrustError } from "../web/lib/catfood-trust";
import { CATFOOD_ROLE_ACTION_DOMAIN, CATFOOD_ROLE_ACTION_INTENT_PURPOSE, CatfoodRoleAuthority, assertLocalRoleSession, initializeRoleAuthorityStore, localRoleEvidence, performRoleAction, registerLocalRoleSessionForTest, roleChannelPublicKeyFingerprint, verifyRoleActionReceiptV2, verifyRoleEvidenceV4, type RoleChannelBinding, type RoleRunScope, type WriterCredentialReference } from "../web/lib/catfood-role-channel";
import { addIndependentAttestationV4Store } from "../web/lib/catfood-independent-attestation";
import { initializeIndependentAttestationStore as initializeLegacyAttestationStore } from "../web/lib/catfood-independent-attestation-v3";

const hash = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const decodeEnvelope = (value: string) => JSON.parse(Buffer.from(JSON.parse(value).payload, "base64url").toString()) as Record<string, any>;

type Harness = ReturnType<typeof harness>;
function harness() {
  const dir = mkdtempSync(join(tmpdir(), "catfood-role-channel-")), path = join(dir, "authority.db"); writeFileSync(path, ""); const authorityKey = generateKeyPairSync("ed25519"), now = { value: Date.parse("2026-10-01T00:00:00.000Z") };
  const binding: RoleChannelBinding = { trust_domain: "TEST_ONLY", issuer: "fixture-role-authority", issuer_key_id: "authority:v4", audience: "ikorabu-catfood", origin: "http://127.0.0.1:32199", credential: "fixture-coarse-service-access-credential", authority_public_key_pem: authorityKey.publicKey.export({ type: "spki", format: "pem" }).toString(), enrollment_namespace: "fixture:role-channel", build_policy_sha256: CATFOOD_POLICY_SHA256, accepted_snapshot_id: "snapshot:role-channel", accepted_snapshot_sha256: roleChannelAcceptedSnapshotDigest(), policy: { policy_id: "fixture-policy-v1", session_lifetime_ms: 60_000, registration_challenge_lifetime_ms: 5_000, action_challenge_lifetime_ms: 5_000, maximum_outstanding_requests: 16, receipt_retention_ms: 86_400_000 } };
  const scope: RoleRunScope = { environment_type: "test", environment_instance_id: "instance:test", deployment_id: "deployment:test", organization_id: "org:test", tenant_id: "org:test", account_id: "acct_test", run_id: "run:test", spec_sha256: "4".repeat(64) };
  initializeRoleAuthorityStore(path, binding); let authority = new CatfoodRoleAuthority(path, binding, authorityKey.privateKey, () => now.value);
  return { dir, path, binding, scope, now, authorityKey, get authority() { return authority; }, restart() { authority.close(); authority = new CatfoodRoleAuthority(path, binding, authorityKey.privateKey, () => now.value); }, close() { authority.close(); rmSync(dir, { recursive: true, force: true }); } };
}

function enrollmentBinding(f: Harness, role: CatfoodEnrollmentRole, writer?: WriterCredentialReference): TestEnrollmentBinding { return { trust_domain: "TEST_ONLY", issuer: f.binding.issuer, issuer_key_id: f.binding.issuer_key_id, audience: f.binding.audience, origin: f.binding.origin, credential: f.binding.credential, public_key_pem: f.binding.authority_public_key_pem, environment_identity: f.scope.environment_instance_id, deployment_id: f.scope.deployment_id, enrollment_namespace: f.binding.enrollment_namespace, build_policy_sha256: f.binding.build_policy_sha256, accepted_snapshot_id: f.binding.accepted_snapshot_id, accepted_snapshot_sha256: f.binding.accepted_snapshot_sha256, launch_ticket: `launch:${role}`, writer_signing_key_id: writer?.key_id ?? "none", writer_signing_key_version: writer?.key_version ?? "none", writer_signing_public_key_pem: writer?.public_key_pem ?? f.binding.authority_public_key_pem }; }

function enroll(f: Harness, role: CatfoodEnrollmentRole, actionKeys = generateKeyPairSync("ed25519"), outerKeys = generateKeyPairSync("ed25519")) {
  const outerPublic = outerKeys.publicKey.export({ type: "spki", format: "pem" }).toString(), writer = role === "writer" ? { key_id: "attest:test:v4", key_version: "v4", public_key_sha256: roleChannelPublicKeyFingerprint(outerPublic), public_key_pem: outerPublic } : undefined, binding = enrollmentBinding(f, role, writer), subject = collectCurrentRuntimeSubject(binding), launch = observeTestOnlyRoleLaunch(binding, role, subject), assignment = f.authority.issueLaunchKeyAssignment({ role, scope: f.scope, subject, launch, descriptor: roleChannelArtifactDescriptor(role), public_key_pem: actionKeys.publicKey.export({ type: "spki", format: "pem" }).toString(), writer_credential: writer }), session = registerLocalRoleSessionForTest({ binding: f.binding, transport: f.authority.transport, assignment_envelope: assignment, private_key: actionKeys.privateKey, now: () => f.now.value });
  return { role, subject, launch, assignment, session, actionKeys, outerKeys, writer, evidence: localRoleEvidence(session), enrollment: decodeEnvelope(String(localRoleEvidence(session).enrollment_envelope_json)) };
}

function request(f: Harness, path: string, body: Record<string, unknown>, bearer = f.binding.credential) { return f.authority.transport({ method: "POST", url: new URL(path, f.binding.origin).toString(), headers: { Accept: "application/json", Authorization: `Bearer ${bearer}`, "Content-Type": "application/json" }, body: canonicalJson(body), timeout_ms: 1_000, maximum_bytes: 2_000_000 }); }

function evaluatorBody(f: Harness, assessment: string) { const core = { verdict: "FAIL" }; return { schema: "catfood-evaluation-action.v2", action_id: assessment, assessment_id: assessment, run_id: f.scope.run_id, run_scope: f.scope, decision_core: core, decision_core_sha256: hash(canonicalJson(core)), role_evidence_sha256: "1".repeat(64), evaluator: { session_id: "test" }, bundle_sha256: "2".repeat(64), source_digest: "3".repeat(64), policy_sha256: CATFOOD_POLICY_SHA256 }; }

function rawAction(f: Harness, actor: ReturnType<typeof enroll>, input: { action: string; purpose: CatfoodActionPurpose; request_id: string; logical_target?: string; body(reserved: string): Record<string, unknown>; intent?: (proof: Record<string, any>) => void; proof?: (proof: Record<string, any>) => void; defer?: boolean }) {
  const enrollment = actor.enrollment, launch = enrollment.launch, subjectSha = hash(canonicalJson(enrollment.subject)), intent: Record<string, any> = { domain: CATFOOD_ROLE_ACTION_INTENT_PURPOSE, audience: f.binding.audience, origin: new URL(f.binding.origin).origin, method: "POST", path: "/v4/catfood/actions/challenge", session_id: enrollment.session_id, action_key_fingerprint: enrollment.action_key_fingerprint, asserted_role: actor.role, subject_sha256: subjectSha, launch_id: launch.launch_id, accepted_snapshot_id: enrollment.accepted_snapshot_id, accepted_snapshot_sha256: enrollment.accepted_snapshot_sha256, purpose_class: input.purpose, action: input.action, scope: f.scope, request_id: input.request_id, logical_target: input.logical_target ?? f.scope.run_id }; input.intent?.(intent); const intent64 = Buffer.from(canonicalJson(intent)).toString("base64url"), challengeResponse = request(f, "/v4/catfood/actions/challenge", { schema: "catfood-role-action-intent.v1", proof_base64url: intent64, signature_base64url: sign(null, Buffer.from(`${CATFOOD_ROLE_ACTION_INTENT_PURPOSE}\n${intent64}`), actor.actionKeys.privateKey).toString("base64url") }), challenge = decodeEnvelope(String(challengeResponse.body)), body = input.body(challenge.reserved_action_id), bodyJson = canonicalJson(body), proof: Record<string, any> = { domain: CATFOOD_ROLE_ACTION_DOMAIN, issuer: f.binding.issuer, audience: f.binding.audience, origin: new URL(f.binding.origin).origin, method: "POST", path: "/v4/catfood/actions", content_type: "application/json", body_byte_length: Buffer.byteLength(bodyJson), body_sha256: hash(bodyJson), session_id: enrollment.session_id, action_key_fingerprint: enrollment.action_key_fingerprint, asserted_role: actor.role, subject_sha256: subjectSha, launch_id: launch.launch_id, accepted_snapshot_id: enrollment.accepted_snapshot_id, accepted_snapshot_sha256: enrollment.accepted_snapshot_sha256, purpose_class: input.purpose, action: input.action, scope: f.scope, request_id: input.request_id, reserved_action_id: challenge.reserved_action_id, nonce_id: challenge.nonce_id, nonce: challenge.nonce, not_before: challenge.not_before, expires_at: challenge.expires_at }; input.proof?.(proof); const proof64 = Buffer.from(canonicalJson(proof)).toString("base64url"), wire = { schema: "catfood-role-action.v1", proof_base64url: proof64, body_json: bodyJson, signature_base64url: sign(null, Buffer.from(`${CATFOOD_ROLE_ACTION_DOMAIN}\n${proof64}`), actor.actionKeys.privateKey).toString("base64url") }; return input.defer ? { wire, challenge } : { wire, challenge, response: request(f, "/v4/catfood/actions", wire) };
}

describe("WP3 role-channel V4 authority", () => {
  test("T01-T06 copied public evidence, shared bearer, outer key and wrong-role proofs cannot create E", () => { const f = harness(); try {
    const evaluator = enroll(f, "evaluator"), writer = enroll(f, "writer");
    expect(() => request(f, "/v4/catfood/actions", { schema: "catfood-role-action.v1", proof_base64url: "copied", body_json: canonicalJson(evaluatorBody(f, "assessment:copied")), signature_base64url: "copied" })).toThrow();
    expect(() => request(f, "/v3/catfood/enrollment/status", { requested_role: "evaluator", action: "evaluator.result.commit" })).toThrow("ROLE_CHANNEL_PATH_INVALID");
    expect(() => request(f, "/v4/catfood/enrollment", { schema: "catfood-role-registration.v1", assignment_envelope: evaluator.assignment, challenge_envelope: evaluator.assignment, proof_base64url: "outer", signature_base64url: sign(null, Buffer.from("outer"), writer.outerKeys.privateKey).toString("base64url") })).toThrow();
    expect(() => rawAction(f, writer, { action: "evaluator.result.commit", purpose: "INDEPENDENT_EVALUATION", request_id: "writer-forge-e", body: (id) => evaluatorBody(f, id) })).toThrow("ROLE_ACTION_UNAUTHORIZED");
    expect(() => rawAction(f, evaluator, { action: "evaluator.result.commit", purpose: "INDEPENDENT_EVALUATION", request_id: "conflicting-role", intent: (proof) => { proof.asserted_role = "writer"; }, body: (id) => evaluatorBody(f, id) })).toThrow("ROLE_ACTION_UNAUTHORIZED");
    expect(Object.keys(evaluator.session)).toEqual(["role"]); expect(JSON.stringify(evaluator.session)).not.toContain("PRIVATE"); expect((evaluator.session as any).sign).toBeUndefined(); expect(() => assertLocalRoleSession({ role: "evaluator" }, "evaluator")).toThrow("LOCAL_ROLE_SESSION_INVALID"); expect(() => verifyRoleEvidenceV4(evaluator.evidence, { ...f.binding, trust_domain: "OPERATIONAL", origin: "https://authority.invalid" }, "evaluator", f.scope)).toThrow("ROLE_EVIDENCE_INVALID");
  } finally { f.close(); } });

  test("T07-T09 exact replay is one durable effect while body, path, purpose, run and result substitution reject", () => { const f = harness(); try {
    const evaluator = enroll(f, "evaluator"), first = rawAction(f, evaluator, { action: "evaluator.result.commit", purpose: "INDEPENDENT_EVALUATION", request_id: "evaluation-a", body: (id) => evaluatorBody(f, id) }), original = first.response!.body!;
    expect(request(f, "/v4/catfood/actions", first.wire).body).toBe(original);
    expect(() => request(f, "/v4/catfood/actions", { ...first.wire, body_json: canonicalJson({ ...JSON.parse(first.wire.body_json), decision_core: { verdict: "PASS" } }) })).toThrow("ROLE_ACTION_CONFLICT");
    expect(() => request(f, "/v4/catfood/actions/other", first.wire)).toThrow("ROLE_CHANNEL_PATH_INVALID");
    expect(() => rawAction(f, evaluator, { action: "evaluator.result.commit", purpose: "INDEPENDENT_EVALUATION", request_id: "run-b", intent: (proof) => { proof.scope = { ...f.scope, run_id: "run:B" }; }, body: (id) => evaluatorBody(f, id) })).toThrow("ROLE_ACTION_UNAUTHORIZED");
    expect(() => rawAction(f, evaluator, { action: "evaluator.result.commit", purpose: "ATTESTATION", request_id: "wrong-purpose", body: (id) => evaluatorBody(f, id) })).toThrow("ROLE_ACTION_UNAUTHORIZED");
    const db = new Database(f.path, { readonly: true }); expect(db.query<{ n: number }, []>("SELECT COUNT(*) n FROM role_action_requests").get()!.n).toBe(1); db.close();
  } finally { f.close(); } });

  test("T07/T10/T11 expiry, revocation, lost response and authority restart preserve historical receipts without new authority", () => { const f = harness(); try {
    const evaluator = enroll(f, "evaluator"), committed = rawAction(f, evaluator, { action: "evaluator.result.commit", purpose: "INDEPENDENT_EVALUATION", request_id: "lost-response", body: (id) => evaluatorBody(f, id) }), receipt = JSON.parse(committed.response!.body!); f.restart(); expect(request(f, "/v4/catfood/actions", committed.wire).body).toBe(committed.response!.body); f.now.value += 60_001; expect(verifyRoleActionReceiptV2(receipt, f.binding, { role: "evaluator", action: "evaluator.result.commit", purpose_class: "INDEPENDENT_EVALUATION", scope: f.scope }).action_id).toBe(decodeEnvelope(receipt.envelope_json).action_id); expect(() => performRoleAction(evaluator.session, { action: "evaluator.result.commit", purpose_class: "INDEPENDENT_EVALUATION", request_id: "expired-new", logical_target: f.scope.run_id, body: (id) => evaluatorBody(f, id) })).toThrow("LOCAL_ROLE_SESSION_INVALID");
    const fresh = harness(); try { const actor = enroll(fresh, "evaluator"), sessionId = actor.enrollment.session_id; fresh.authority.revokeSession(sessionId); expect(() => rawAction(fresh, actor, { action: "evaluator.result.commit", purpose: "INDEPENDENT_EVALUATION", request_id: "revoked-new", body: (id) => evaluatorBody(fresh, id) })).toThrow("ROLE_ACTION_UNAUTHORIZED"); } finally { fresh.close(); }
  } finally { f.close(); } });

  test("T12-T14 evaluator cannot issue and writer cannot evaluate; correct writer credential action succeeds", () => { const f = harness(); try {
    const evaluator = enroll(f, "evaluator"), writer = enroll(f, "writer"), writerEvidence = { key_id: writer.writer!.key_id, key_version: writer.writer!.key_version, public_key_sha256: writer.writer!.public_key_sha256 }, writerBody = (id: string) => ({ schema: "catfood-writer-credential-action.v2", action_id: id, run_id: f.scope.run_id, writer: { session_id: writer.enrollment.session_id }, writer_credential: writerEvidence, role_evidence_sha256: "1".repeat(64) });
    expect(() => rawAction(f, evaluator, { action: "writer.credential.authorize", purpose: "ATTESTATION", request_id: "evaluator-writer", body: writerBody })).toThrow("ROLE_ACTION_UNAUTHORIZED");
    expect(() => rawAction(f, evaluator, { action: "writer.issuance.prepare", purpose: "ATTESTATION", request_id: "evaluator-prepare", body: (id) => ({ action_id: id, run_id: f.scope.run_id }) })).toThrow("ROLE_ACTION_UNAUTHORIZED");
    expect(() => rawAction(f, writer, { action: "evaluator.result.commit", purpose: "INDEPENDENT_EVALUATION", request_id: "writer-evaluator", body: (id) => evaluatorBody(f, id) })).toThrow("ROLE_ACTION_UNAUTHORIZED");
    const result = rawAction(f, writer, { action: "writer.credential.authorize", purpose: "ATTESTATION", request_id: "writer-credential", body: writerBody }); expect(JSON.parse(result.response!.body!).schema).toBe("catfood-action-receipt.v2");
  } finally { f.close(); } });

  test("assignment, nonce, key and request identity are one-shot and bounded", () => { const f = harness(); try {
    const pair = generateKeyPairSync("ed25519"), first = enroll(f, "evaluator", pair), replay = registerLocalRoleSessionForTest({ binding: f.binding, transport: f.authority.transport, assignment_envelope: first.assignment, private_key: pair.privateKey, now: () => f.now.value }); expect(localRoleEvidence(replay).enrollment_envelope_json).toBe(first.evidence.enrollment_envelope_json);
    const writerBinding = enrollmentBinding(f, "writer"), wrongLaunch = observeTestOnlyRoleLaunch(writerBinding, "writer", first.subject); expect(() => f.authority.issueLaunchKeyAssignment({ role: "writer", scope: f.scope, subject: first.subject, launch: wrongLaunch, descriptor: roleChannelArtifactDescriptor("writer"), public_key_pem: pair.publicKey.export({ type: "spki", format: "pem" }).toString(), writer_credential: { key_id: "x", key_version: "v1", public_key_sha256: roleChannelPublicKeyFingerprint(f.binding.authority_public_key_pem), public_key_pem: f.binding.authority_public_key_pem } })).toThrow("ROLE_ASSIGNMENT_KEY_REUSED");
    const pending = rawAction(f, first, { action: "evaluator.result.commit", purpose: "INDEPENDENT_EVALUATION", request_id: "expired-nonce", body: (id) => evaluatorBody(f, id), defer: true }); f.now.value += 5_001; expect(() => request(f, "/v4/catfood/actions", pending.wire)).toThrow("ROLE_ACTION_UNAUTHORIZED");
    expect(() => rawAction(f, first, { action: "evaluator.result.commit", purpose: "INDEPENDENT_EVALUATION", request_id: "expired-nonce", logical_target: "changed", body: (id) => evaluatorBody(f, id) })).toThrow("ROLE_ACTION_CONFLICT");
  } finally { f.close(); } });

  test("V3 rows remain diagnostic while an additive create-only V4 namespace is installed", () => { const dir = mkdtempSync(join(tmpdir(), "catfood-v4-upgrade-")), path = join(dir, "attestation.db"), key = generateKeyPairSync("ed25519"), publicKey = key.publicKey.export({ type: "spki", format: "pem" }).toString(), config = { writer_identity: "attestor:test", signing_key_id: "attest:test", signing_public_key_pem: publicKey }; try { writeFileSync(path, ""); initializeLegacyAttestationStore(path, config); const legacy = new Database(path, { readonly: true }), before = legacy.query<Record<string, unknown>, []>("SELECT * FROM attestation_meta").get()!; legacy.close(); addIndependentAttestationV4Store(path, config); const db = new Database(path, { readonly: true }); expect(db.query<Record<string, unknown>, []>("SELECT * FROM attestation_meta").get()).toEqual(before); expect(db.query<Record<string, unknown>, []>("SELECT * FROM attestation_v4_meta").get()!.schema_version).toBe("catfood-independent-attestation.v4"); expect(() => db.exec("UPDATE attestation_v4_meta SET writer_identity='changed'")).toThrow(); db.close(); } finally { rmSync(dir, { recursive: true, force: true, maxRetries: 5, retryDelay: 20 }); } });
});
