import { describe, expect, test } from "bun:test";
import { generateKeyPairSync, sign } from "node:crypto";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { canonicalJson } from "../web/lib/catfood-harness";
import { roleChannelAcceptedSnapshotDigest } from "../web/lib/catfood-enrollment";
import { CATFOOD_CAPABILITIES, CATFOOD_GO_SCHEMA, CATFOOD_POLICY_SHA256, CATFOOD_TRUST_SCHEMA, ProtectedCatfoodCustodian, createCatfoodRunSpec, initializeProtectedCatfoodStores, type CatfoodTrustConfig, type HumanGoPayload, type RunnerSession } from "../web/lib/catfood-trust";
import { CATFOOD_THREADS_PINS } from "../web/lib/catfood-coe";
import { CatfoodRoleAuthority, initializeRoleAuthorityStore, type RoleChannelBinding, type RoleRunScope } from "../web/lib/catfood-role-channel";
import { FixtureThreadsSource, TestClock } from "./catfood-trust-fixture";

const BOUNDARY = "57d896aa756387048b70dc016e482274d571dd165866416e3fc480d59a97e8cf", IKORABU = "c".repeat(40);

function closedRun(expected: "PASS" | "FAIL" = "PASS") {
  const dir = mkdtempSync(join(tmpdir(), "catfood-v4-run-")), control = join(dir, "control.db"), checkpoint = join(dir, "checkpoint.db"); writeFileSync(control, ""); writeFileSync(checkpoint, "");
  const go = generateKeyPairSync("ed25519"), clock = new TestClock(), run_id = `run-v4-${Math.random().toString(16).slice(2)}`;
  const trust: CatfoodTrustConfig = { schema: CATFOOD_TRUST_SCHEMA, custodian_identity: "custodian:test", environment_type: "test", environment_instance_id: "instance:test", organization_id: "org:test", tenant_id: "org:test", account_id: "acct_test", ikorabu_release_sha: IKORABU, threads_sha: CATFOOD_THREADS_PINS.threads_sha, operational_boundary_sha256: BOUNDARY, threads_release_sha256: CATFOOD_THREADS_PINS.release_sha256, wp1_sha256: CATFOOD_THREADS_PINS.wp1_sha256, coe_sha256: CATFOOD_THREADS_PINS.coe_sha256, rehearsal_attestation_sha256: CATFOOD_THREADS_PINS.rehearsal_attestation_sha256, emitter_inventory_sha256: CATFOOD_THREADS_PINS.emitter_inventory_sha256, threads_schema: 33, threads_schema_fingerprint: CATFOOD_THREADS_PINS.schema_fingerprint, source_mode: "TEST_ONLY", go_keys: [{ key_id: "go:test", public_key_pem: go.publicKey.export({ type: "spki", format: "pem" }).toString(), trust_class: "TEST_ONLY" }] };
  const spec = createCatfoodRunSpec({ run_id, environment_type: "test", environment_instance_id: trust.environment_instance_id, organization_id: trust.organization_id, tenant_id: trust.tenant_id, account_id: trust.account_id, capabilities: CATFOOD_CAPABILITIES, effective_config_sha256: "4".repeat(64), ikorabu_release_sha: IKORABU, threads_sha: trust.threads_sha, operational_boundary_sha256: BOUNDARY, threads_release_sha256: trust.threads_release_sha256, wp1_sha256: trust.wp1_sha256, coe_sha256: trust.coe_sha256, rehearsal_attestation_sha256: trust.rehearsal_attestation_sha256, emitter_inventory_sha256: trust.emitter_inventory_sha256, threads_schema: 33, threads_schema_fingerprint: trust.threads_schema_fingerprint, requested_window_start: "2026-09-30T00:00:00Z", requested_window_end: "2026-10-01T00:00:00Z" });
  const payload: HumanGoPayload = { schema: CATFOOD_GO_SCHEMA, grant_id: `grant:${run_id}`, nonce: `nonce:${run_id}`, run_id, spec_hash: spec.spec_sha256, environment_type: spec.environment_type, environment_instance_id: spec.environment_instance_id, organization_id: spec.organization_id, tenant_id: spec.tenant_id, account_id: spec.account_id, capabilities: CATFOOD_CAPABILITIES, valid_from: new Date(clock.wallMs - 1_000).toISOString(), valid_until: new Date(clock.wallMs + 90_000_000).toISOString(), maximum_duration_seconds: 86_400, maximum_wp3_epoch: 2, acceptance_policy_sha256: CATFOOD_POLICY_SHA256, threads_sha: trust.threads_sha, operational_boundary_sha256: BOUNDARY, threads_release_sha256: trust.threads_release_sha256, threads_schema: 33, ikorabu_release_sha: IKORABU, paid_provider_allowance: "ZERO" }, bytes = Buffer.from(canonicalJson(payload)), artifact = canonicalJson({ algorithm: "Ed25519", key_id: "go:test", payload: bytes.toString("base64url"), signature: sign(null, bytes, go.privateKey).toString("base64url") });
  initializeProtectedCatfoodStores(control, checkpoint, trust, clock.sample().wall_time); const source = new FixtureThreadsSource(clock, trust.threads_sha, trust.threads_release_sha256), custodian = new ProtectedCatfoodCustodian(control, checkpoint, source, clock); custodian.createRun(spec, artifact);
  const work = (session: RunnerSession, capability: "editorial.cycle" | "editorial.outcome_evaluation" | "threads.publish.dry_run", sourceId: string) => { const ticket = custodian.admit(session, capability, sourceId); source.complete(ticket.claim_id); custodian.reconcile(session, ticket.work_id); };
  const first = custodian.issueOwnerSession(run_id); custodian.armObservation(first, { kind: "TEST_ONLY_EXPLICIT", cadence_seconds: 30, maximum_gap_seconds: 60, clock_mapping: "SAME_TEST_CLOCK" }); custodian.activate(first, custodian.preflight(first)); work(first, "editorial.cycle", "cycle:one"); custodian.stop(first, "STOP"); clock.advance(121_000); const second = custodian.issueOwnerSession(run_id); custodian.takeover(run_id, second); custodian.activate(second, custodian.preflight(second)); work(second, "editorial.outcome_evaluation", "outcome:one"); if (expected === "PASS") work(second, "threads.publish.dry_run", "dry:one"); clock.advance(86_400_000); custodian.stop(second, "STOP"); expect(custodian.closeRun(second).verdict).toBe(expected); custodian.close();
  return { dir, control, checkpoint, spec, clock, close() { rmSync(dir, { recursive: true, force: true, maxRetries: 5, retryDelay: 20 }); } };
}

type Child = { process: ReturnType<typeof Bun.spawn>; read(): Promise<any>; send(value: unknown): void; close(): Promise<void> };
function child(script: string): Child {
  const proc = Bun.spawn({ cmd: [process.execPath, resolve(import.meta.dir, `../scripts/${script}`), "--test-role-fixture"], cwd: resolve(import.meta.dir, ".."), stdin: "pipe", stdout: "pipe", stderr: "pipe" });
  const reader = proc.stdout.getReader(), decoder = new TextDecoder(); let buffered = "";
  return { process: proc, send(value) { proc.stdin.write(canonicalJson(value as never) + "\n"); proc.stdin.flush(); }, async read() { while (!buffered.includes("\n")) { const part = await reader.read(); if (part.done) throw new Error(`role child exited: ${await new Response(proc.stderr).text()}`); buffered += decoder.decode(part.value, { stream: true }); } const at = buffered.indexOf("\n"), line = buffered.slice(0, at); buffered = buffered.slice(at + 1); return JSON.parse(line); }, async close() { proc.stdin.end(); await proc.exited; } };
}

describe("WP3 V4 separated role processes", () => {
  test("sealed source -> evaluator PoP -> writer issuance -> clean verifier", async () => {
    const run = closedRun(), authorityFile = join(run.dir, "role-authority.db"), writerStore = join(run.dir, "writer-v4.db"); writeFileSync(authorityFile, ""); writeFileSync(writerStore, ""); const authorityKeys = generateKeyPairSync("ed25519"); let authority!: CatfoodRoleAuthority;
    const authorityErrors: string[] = [], server = Bun.serve({ port: 0, async fetch(request) { try { const body = await request.text(), result = authority.transport({ method: "POST", url: request.url, headers: { Accept: request.headers.get("accept") ?? "", Authorization: request.headers.get("authorization") ?? "", "Content-Type": request.headers.get("content-type") ?? "" }, body, timeout_ms: 2_500, maximum_bytes: 2_000_000 }); return new Response(result.body, { status: result.status, headers: { "content-type": result.content_type } }); } catch (error) { authorityErrors.push(error instanceof Error ? error.message : String(error)); return Response.json({ error: authorityErrors.at(-1) }, { status: 403 }); } } });
    const binding: RoleChannelBinding = { trust_domain: "TEST_ONLY", issuer: "fixture-role-authority", issuer_key_id: "authority:v4", audience: "ikorabu-catfood", origin: `http://127.0.0.1:${server.port}`, credential: "fixture-coarse-service-access-credential", authority_public_key_pem: authorityKeys.publicKey.export({ type: "spki", format: "pem" }).toString(), enrollment_namespace: "fixture:role-channel", build_policy_sha256: CATFOOD_POLICY_SHA256, accepted_snapshot_id: "snapshot:role-channel", accepted_snapshot_sha256: roleChannelAcceptedSnapshotDigest(), policy: { policy_id: "fixture-policy-v1", session_lifetime_ms: 60_000, registration_challenge_lifetime_ms: 30_000, action_challenge_lifetime_ms: 30_000, maximum_outstanding_requests: 32, receipt_retention_ms: 604_800_000 } }, scope: RoleRunScope = { environment_type: "test", environment_instance_id: "instance:test", deployment_id: "deployment:test", organization_id: "org:test", tenant_id: "org:test", account_id: "acct_test", run_id: run.spec.run_id, spec_sha256: run.spec.spec_sha256 };
    initializeRoleAuthorityStore(authorityFile, binding); authority = new CatfoodRoleAuthority(authorityFile, binding, authorityKeys.privateKey, () => run.clock.wallMs);
    const ps = child("catfood-custodian-role.ts"), evaluator = child("catfood-evaluate-role.ts"), writer = child("catfood-issue-role.ts"), verifier = child("catfood-verify-role.ts"), children = [ps, evaluator, writer, verifier];
    try {
      ps.send({ binding, now_ms: run.clock.wallMs }); evaluator.send({ binding, run_id: run.spec.run_id, now_ms: run.clock.wallMs }); writer.send({ binding, now_ms: run.clock.wallMs }); verifier.send({ binding, now_ms: run.clock.wallMs }); const [psHello, eHello, wHello, vHello] = await Promise.all(children.map((item) => item.read()));
      expect(psHello.roles[0].subject.pid).toBe(ps.process.pid); expect(eHello.subject.pid).toBe(evaluator.process.pid); expect(wHello.subject.pid).toBe(writer.process.pid); expect(vHello.subject.pid).toBe(verifier.process.pid); expect(new Set([ps.process.pid, evaluator.process.pid, writer.process.pid, verifier.process.pid]).size).toBe(4);
      const assign = (hello: any) => authority.issueLaunchKeyAssignment({ role: hello.role, scope, subject: hello.subject, launch: hello.launch, descriptor: hello.descriptor, public_key_pem: hello.public_key_pem, writer_credential: hello.writer_credential });
      ps.send({ assignment_envelopes: psHello.roles.map(assign) }); evaluator.send({ assignment_envelope: assign(eHello) }); writer.send({ assignment_envelope: assign(wHello) }); verifier.send({ assignment_envelope: assign(vHello) }); let enrolled: any[]; try { enrolled = await Promise.all([ps.read(), evaluator.read(), writer.read(), verifier.read()]); } catch (error) { throw new Error(`${error instanceof Error ? error.message : String(error)}\nauthority errors: ${authorityErrors.join(" | ")}`); } const [psEnrolled, eEnrolled, wEnrolled] = enrolled, roleEvidence = [...psEnrolled.evidence, eEnrolled.evidence, wEnrolled.evidence];
      evaluator.send({ control_path: run.control, checkpoint_path: run.checkpoint, role_evidence: roleEvidence, now_ms: run.clock.wallMs }); const assessment = await evaluator.read(); expect(authorityErrors).toEqual([]); expect(assessment.package.decision_core).toMatchObject({ verdict: "PASS", test_only: true }); expect(assessment.package.provenance.trust_domain).toBe("TEST_ONLY"); writer.send({ store_path: writerStore, package: assessment.package, now_ms: run.clock.wallMs }); const artifact = await writer.read(), artifactPayload = JSON.parse(JSON.parse(artifact.artifact_json).payload_json); expect(artifactPayload).toMatchObject({ trust_domain: "TEST_ONLY", decision_core: { test_only: true } }); verifier.send({ artifact_json: artifact.artifact_json, run_id: run.spec.run_id, bundle_sha256: artifact.bundle_sha256, now_ms: run.clock.wallMs }); const verified = await verifier.read(); expect(verified).toEqual({ type: "verified", verdict: "PASS" });
      const changedE = JSON.parse(artifact.artifact_json); changedE.evaluation_package.decision_core.verdict = "FAIL"; verifier.send({ artifact_json: canonicalJson(changedE), run_id: run.spec.run_id, bundle_sha256: artifact.bundle_sha256 }); expect((await verifier.read()).type).toBe("rejected"); const changedP = JSON.parse(artifact.artifact_json), payload = JSON.parse(changedP.payload_json); payload.decision_core.verdict = "FAIL"; changedP.payload_json = canonicalJson(payload); verifier.send({ artifact_json: canonicalJson(changedP), run_id: run.spec.run_id, bundle_sha256: artifact.bundle_sha256 }); expect((await verifier.read()).type).toBe("rejected"); verifier.send({ artifact_json: "{}", run_id: run.spec.run_id, bundle_sha256: artifact.bundle_sha256 }); expect(await verifier.read()).toMatchObject({ type: "rejected", code: "ATTESTATION_SCHEMA_INVALID" });
      run.clock.advance(86_400_000); const lateVerifier = child("catfood-verify-role.ts"); children.push(lateVerifier); lateVerifier.send({ binding, now_ms: run.clock.wallMs }); const lateHello = await lateVerifier.read(), lateAssignment = assign(lateHello); lateVerifier.send({ assignment_envelope: lateAssignment }); await lateVerifier.read(); lateVerifier.send({ artifact_json: artifact.artifact_json, run_id: run.spec.run_id, bundle_sha256: artifact.bundle_sha256, now_ms: run.clock.wallMs }); expect(await lateVerifier.read()).toEqual({ type: "verified", verdict: "PASS" }); const evaluationReceipt = JSON.parse(artifact.artifact_json).evaluation_package.evaluation_receipt, evaluationReceiptPayload = JSON.parse(Buffer.from(JSON.parse(evaluationReceipt.envelope_json).payload, "base64url").toString()); expect(() => authority.transport({ method: "POST", url: new URL("/v4/catfood/actions", binding.origin).toString(), headers: { Accept: "application/json", Authorization: `Bearer ${binding.credential}`, "Content-Type": "application/json" }, body: canonicalJson(evaluationReceiptPayload.authenticated_request), timeout_ms: 1_000, maximum_bytes: 2_000_000 })).toThrow("ROLE_ACTION_CONFLICT");
    } finally { await Promise.all(children.map((item) => item.close().catch(() => undefined))); server.stop(true); authority.close(); run.close(); }
  }, 30_000);

  test("T15-T18 genuine FAIL remains FAIL and writer possession cannot replace evaluator judgment", async () => {
    const run = closedRun("FAIL"), authorityFile = join(run.dir, "role-authority-fail.db"), writerStore = join(run.dir, "writer-v4-fail.db"); writeFileSync(authorityFile, ""); writeFileSync(writerStore, ""); const authorityKeys = generateKeyPairSync("ed25519"); let authority!: CatfoodRoleAuthority;
    const server = Bun.serve({ port: 0, async fetch(request) { try { const result = authority.transport({ method: "POST", url: request.url, headers: { Accept: request.headers.get("accept") ?? "", Authorization: request.headers.get("authorization") ?? "", "Content-Type": request.headers.get("content-type") ?? "" }, body: await request.text(), timeout_ms: 2_500, maximum_bytes: 2_000_000 }); return new Response(result.body, { status: result.status, headers: { "content-type": result.content_type } }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : String(error) }, { status: 403 }); } } });
    const binding: RoleChannelBinding = { trust_domain: "TEST_ONLY", issuer: "fixture-role-authority", issuer_key_id: "authority:v4", audience: "ikorabu-catfood", origin: `http://127.0.0.1:${server.port}`, credential: "fixture-coarse-service-access-credential", authority_public_key_pem: authorityKeys.publicKey.export({ type: "spki", format: "pem" }).toString(), enrollment_namespace: "fixture:role-channel", build_policy_sha256: CATFOOD_POLICY_SHA256, accepted_snapshot_id: "snapshot:role-channel", accepted_snapshot_sha256: roleChannelAcceptedSnapshotDigest(), policy: { policy_id: "fixture-policy-v1", session_lifetime_ms: 172_800_000, registration_challenge_lifetime_ms: 30_000, action_challenge_lifetime_ms: 30_000, maximum_outstanding_requests: 32, receipt_retention_ms: 604_800_000 } }, scope: RoleRunScope = { environment_type: "test", environment_instance_id: "instance:test", deployment_id: "deployment:test", organization_id: "org:test", tenant_id: "org:test", account_id: "acct_test", run_id: run.spec.run_id, spec_sha256: run.spec.spec_sha256 };
    initializeRoleAuthorityStore(authorityFile, binding); authority = new CatfoodRoleAuthority(authorityFile, binding, authorityKeys.privateKey, () => run.clock.wallMs); const ps = child("catfood-custodian-role.ts"), evaluator = child("catfood-evaluate-role.ts"), writer = child("catfood-issue-role.ts"), verifier = child("catfood-verify-role.ts"), children = [ps, evaluator, writer, verifier];
    try { ps.send({ binding, now_ms: run.clock.wallMs }); evaluator.send({ binding, run_id: run.spec.run_id, now_ms: run.clock.wallMs }); writer.send({ binding, now_ms: run.clock.wallMs }); verifier.send({ binding, now_ms: run.clock.wallMs }); const [psHello, eHello, wHello, vHello] = await Promise.all(children.map((item) => item.read())), assign = (hello: any) => authority.issueLaunchKeyAssignment({ role: hello.role, scope, subject: hello.subject, launch: hello.launch, descriptor: hello.descriptor, public_key_pem: hello.public_key_pem, writer_credential: hello.writer_credential }); ps.send({ assignment_envelopes: psHello.roles.map(assign) }); evaluator.send({ assignment_envelope: assign(eHello) }); writer.send({ assignment_envelope: assign(wHello) }); verifier.send({ assignment_envelope: assign(vHello) }); const [psEnrolled, eEnrolled, wEnrolled] = await Promise.all([ps.read(), evaluator.read(), writer.read()]); await verifier.read(); evaluator.send({ control_path: run.control, checkpoint_path: run.checkpoint, role_evidence: [...psEnrolled.evidence, eEnrolled.evidence, wEnrolled.evidence], now_ms: run.clock.wallMs }); const assessment = await evaluator.read(); expect(assessment.package.decision_core.verdict).toBe("FAIL"); writer.send({ store_path: writerStore, package: assessment.package, now_ms: run.clock.wallMs }); const artifact = await writer.read(); verifier.send({ artifact_json: artifact.artifact_json, run_id: run.spec.run_id, bundle_sha256: artifact.bundle_sha256, now_ms: run.clock.wallMs }); expect(await verifier.read()).toEqual({ type: "verified", verdict: "FAIL" });
    } finally { await Promise.all(children.map((item) => item.close().catch(() => undefined))); server.stop(true); authority.close(); run.close(); }
  }, 30_000);
});
