export type DashboardIconName =
  | "activity" | "calendar" | "publish" | "metrics" | "clock"
  | "pipeline" | "chart" | "experiment" | "fact" | "hypothesis"
  | "unknown" | "next" | "moon" | "sun";

export function dashboardIcon(name: DashboardIconName, className = "ui-icon"): string {
  const paths: Record<DashboardIconName, string> = {
    activity: '<path d="M4 12h3l2-5 4 10 2-5h5"/>',
    calendar: '<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4m8-4v4M3 10h18"/>',
    publish: '<path d="M12 19V5m-5 5 5-5 5 5"/><path d="M5 19h14"/>',
    metrics: '<path d="M5 19V9m7 10V5m7 14v-7"/>',
    clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
    pipeline: '<circle cx="5" cy="12" r="2"/><circle cx="19" cy="6" r="2"/><circle cx="19" cy="18" r="2"/><path d="M7 12h3a4 4 0 0 0 4-4 2 2 0 0 1 2-2h1M7 12h3a4 4 0 0 1 4 4 2 2 0 0 0 2 2h1"/>',
    chart: '<path d="M4 19V5m0 14h17"/><path d="m7 15 4-4 3 2 5-6"/>',
    experiment: '<path d="M9 3h6m-5 0v5l-5 9a3 3 0 0 0 3 4h8a3 3 0 0 0 3-4l-5-9V3"/><path d="M8 15h8"/>',
    fact: '<circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/>',
    hypothesis: '<path d="M9 18h6m-5 3h4"/><path d="M8 14a7 7 0 1 1 8 0c-1 .7-1.5 1.5-1.5 2h-5c0-.5-.5-1.3-1.5-2Z"/>',
    unknown: '<circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.5 2.5 0 1 1 4 2c-1 .7-1.8 1.2-1.8 2.5M12 17h.01"/>',
    next: '<path d="M5 12h14m-5-5 5 5-5 5"/>',
    moon: '<path d="M20 15.5A8.5 8.5 0 0 1 8.5 4 8.5 8.5 0 1 0 20 15.5Z"/>',
    sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',
  };
  return `<svg class="${className}" viewBox="0 0 24 24" fill="none" aria-hidden="true" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${paths[name]}</svg>`;
}

export const customerDashboardStyles = `
.customer-shell{--c-bg:#f4f7fb;--c-panel:#fff;--c-panel-soft:#f8fafc;--c-raised:#fff;--c-text:#111827;--c-text-2:#334155;--c-muted:#64748b;--c-faint:#94a3b8;--c-line:#e2e8f0;--c-line-soft:#edf2f7;--c-brand:#1d4ed8;--c-brand-2:#4338ca;--c-green:#059669;--c-amber:#b45309;--c-purple:#7c3aed;--c-shadow:0 12px 32px rgba(15,23,42,.07);background:var(--c-bg);color:var(--c-text);transition:background .2s ease,color .2s ease}
html[data-customer-theme="dark"]{color-scheme:dark}html[data-customer-theme="dark"] .customer-shell{--c-bg:#080d18;--c-panel:#111827;--c-panel-soft:#172033;--c-raised:#141d2d;--c-text:#f8fafc;--c-text-2:#d7e0ed;--c-muted:#a6b3c5;--c-faint:#7f8da3;--c-line:#293449;--c-line-soft:#202b3d;--c-brand:#82a5ff;--c-brand-2:#a5b4fc;--c-green:#4ade80;--c-amber:#fbbf24;--c-purple:#c4b5fd;--c-shadow:0 16px 38px rgba(0,0,0,.28)}
.customer-shell .app{background:radial-gradient(circle at 80% 0,rgba(59,130,246,.08),transparent 33%),var(--c-bg)}
.customer-shell .sidebar{background:color-mix(in srgb,var(--c-panel) 94%,transparent);border:1px solid var(--c-line);box-shadow:var(--c-shadow)}
.customer-shell .sidebar-header .brand,.customer-shell .nav-item,.customer-shell strong,.customer-shell b{color:var(--c-text)}
.customer-shell .brand-sub,.customer-shell .sys-status-label{color:var(--c-muted)}
.customer-shell .nav-item:hover{background:var(--c-panel-soft);color:var(--c-text)}
.customer-shell .nav-item.active{background:linear-gradient(135deg,#111827,#1e3a8a);color:#fff}
html[data-customer-theme="dark"] .customer-shell .nav-item.active{background:linear-gradient(135deg,#1d4ed8,#312e81)}
.customer-shell .sys-status-card{background:var(--c-panel-soft);border-color:var(--c-line)}
.customer-dashboard{max-width:1480px}
.customer-hero{position:relative;overflow:hidden;align-items:center;padding:22px 24px;margin-bottom:14px;border:1px solid var(--c-line);border-radius:22px;background:linear-gradient(120deg,var(--c-panel) 0%,var(--c-panel) 54%,color-mix(in srgb,var(--c-brand) 10%,var(--c-panel)) 100%);box-shadow:var(--c-shadow)}
.customer-hero:after{content:'';position:absolute;width:280px;height:280px;right:-90px;top:-150px;border-radius:50%;border:42px solid color-mix(in srgb,var(--c-brand) 7%,transparent);pointer-events:none}
.hero-main,.hero-actions{position:relative;z-index:1}.hero-main h1{color:var(--c-text)}.hero-main>p{color:var(--c-text-2)}.account-line{color:var(--c-muted)}
.hero-actions{display:flex;align-items:stretch;gap:9px}.hero-update{min-width:180px;background:color-mix(in srgb,var(--c-panel) 88%,transparent);border-color:var(--c-line)}.hero-update span,.hero-update small{color:var(--c-faint)}.hero-update b{color:var(--c-text-2)}
.theme-toggle{display:flex;align-items:center;gap:8px;border:1px solid var(--c-line);border-radius:14px;padding:0 13px;background:var(--c-panel);color:var(--c-text-2);font:inherit;font-size:10px;font-weight:800;cursor:pointer;box-shadow:0 6px 18px rgba(15,23,42,.05)}.theme-toggle:hover{border-color:color-mix(in srgb,var(--c-brand) 45%,var(--c-line));color:var(--c-brand)}.theme-toggle .theme-sun{display:none}html[data-customer-theme="dark"] .theme-toggle .theme-sun{display:block}html[data-customer-theme="dark"] .theme-toggle .theme-moon{display:none}.ui-icon{width:18px;height:18px;display:block;flex:none}
.now-grid{grid-template-columns:1.25fr repeat(4,1fr);gap:10px}.now-card{position:relative;overflow:hidden;min-height:126px;padding:17px;background:var(--c-panel);border-color:var(--c-line);box-shadow:var(--c-shadow)}.now-card.primary{background:linear-gradient(145deg,#111827,#1e3a8a 68%,#3730a3)}.now-card .summary-top{display:flex;justify-content:space-between;align-items:center}.summary-icon{width:34px;height:34px;display:grid;place-items:center;border-radius:11px;background:color-mix(in srgb,var(--c-brand) 10%,var(--c-panel-soft));color:var(--c-brand)}.primary .summary-icon{background:rgba(255,255,255,.13);color:#bfdbfe}.now-card .summary-value{font-size:24px;letter-spacing:-.035em;margin:13px 0 3px;line-height:1.08}.now-card .summary-value.textual{font-size:14px;line-height:1.4}.now-card .summary-label{color:var(--c-muted);font-size:9px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.now-card small{color:var(--c-faint)}
.workflow-section{background:var(--c-panel);box-shadow:var(--c-shadow);border:1px solid var(--c-line);padding:17px 19px}.workflow-copy span{color:var(--c-faint)}.workflow-copy b{color:var(--c-text-2)}.journey i{background:var(--c-line)}.journey-step{color:var(--c-faint)}.journey-step span{position:relative;width:30px;height:30px;background:var(--c-panel-soft);color:var(--c-muted)}.journey-step span em{position:absolute;right:-6px;top:-7px;min-width:16px;height:16px;padding:0 4px;border-radius:8px;display:grid;place-items:center;background:var(--c-raised);border:1px solid var(--c-line);color:var(--c-text-2);font-size:7px;font-style:normal;box-shadow:0 3px 8px rgba(15,23,42,.1)}.journey-step.done{color:var(--c-green)}.journey-step.done span{background:color-mix(in srgb,var(--c-green) 14%,var(--c-panel));color:var(--c-green)}.journey-step.active{color:var(--c-brand)}.journey-step.active span{background:color-mix(in srgb,var(--c-brand) 15%,var(--c-panel));color:var(--c-brand);box-shadow:0 0 0 4px color-mix(in srgb,var(--c-brand) 8%,transparent)}
.pipeline-section,.performance-section,.report-section,.manual-sync,.visuals-section{background:var(--c-panel);border:1px solid var(--c-line);box-shadow:var(--c-shadow)}.section-header h2{color:var(--c-text)}.section-lead{color:var(--c-muted)}.card-eyebrow{color:var(--c-muted)}.count-pill{background:var(--c-panel-soft);color:var(--c-text-2)}
.pipeline-head{display:none}.pipeline-list{border:0;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:18px}.pipeline-row{display:block;min-width:0!important;padding:15px;border:1px solid var(--c-line);border-radius:15px;background:var(--c-raised);box-shadow:0 5px 18px rgba(15,23,42,.035)}.pipeline-row:hover,.pipeline-row:focus{background:var(--c-panel-soft);border-color:color-mix(in srgb,var(--c-brand) 35%,var(--c-line));transform:translateY(-1px)}.pipeline-card-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.pipeline-topic .topic-name{font-size:13px;color:var(--c-text)}.pipeline-topic small,.schedule-cell small{color:var(--c-faint)}.pipeline-card-head .detail-button{flex:none}.pipeline-card-meta{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:13px}.pipeline-meta{padding:9px;border-radius:10px;background:var(--c-panel-soft);min-width:0}.pipeline-meta>span{display:block;color:var(--c-faint);font-size:7.5px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;margin-bottom:5px}.pipeline-meta b{display:block;font-size:9.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pipeline-card-metrics{margin-top:11px;padding-top:10px;border-top:1px solid var(--c-line-soft)}.origin-chip{background:color-mix(in srgb,var(--c-brand) 11%,var(--c-panel));color:var(--c-brand)}.detail-button,.measuring{background:var(--c-panel-soft);color:var(--c-muted)}
.actual-metric{background:color-mix(in srgb,var(--c-green) 10%,var(--c-panel));color:color-mix(in srgb,var(--c-green) 82%,var(--c-text))}.actual-metric b{color:var(--c-green)}.actual-metric.normalized{background:color-mix(in srgb,var(--c-brand) 10%,var(--c-panel));color:var(--c-brand)}.actual-metric.normalized b{color:var(--c-brand)}.actual-metric.unavailable{background:var(--c-panel-soft);color:var(--c-faint)}.actual-metric.unavailable b,.metric-updated{color:var(--c-faint)}
.kpi-grid{grid-template-columns:repeat(6,1fr);gap:9px}.kpi-card{position:relative;overflow:hidden;min-height:125px;background:var(--c-raised);border-color:var(--c-line);padding:14px}.kpi-card>span{color:var(--c-muted)}.kpi-card strong{color:var(--c-text);font-size:24px}.kpi-card small{color:var(--c-faint)}.kpi-visual{height:28px;margin-top:auto;display:flex;align-items:flex-end}.kpi-visual svg{width:100%;height:28px;overflow:visible}.kpi-visual polyline{fill:none;stroke:var(--c-brand);stroke-width:2;vector-effect:non-scaling-stroke}.kpi-visual circle{fill:var(--c-panel);stroke:var(--c-brand);stroke-width:1.5;vector-effect:non-scaling-stroke}.kpi-measured{width:100%;height:4px;border-radius:4px;background:var(--c-panel-soft);overflow:hidden}.kpi-measured i{display:block;height:100%;border-radius:4px;background:linear-gradient(90deg,var(--c-brand),var(--c-purple))}
.visuals-section{padding:22px}.chart-grid{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(260px,.7fr);gap:12px;margin-top:17px}.chart-card{border:1px solid var(--c-line);border-radius:15px;padding:16px;background:var(--c-raised)}.chart-title{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.chart-title>div{display:flex;align-items:center;gap:9px}.chart-title .summary-icon{width:30px;height:30px}.chart-title b{font-size:11px}.chart-title small{font-size:8.5px;color:var(--c-faint)}.bar-chart{display:grid;gap:10px}.bar-row{display:grid;grid-template-columns:minmax(90px,150px) 1fr auto;gap:10px;align-items:center}.bar-label{font-size:9.5px;color:var(--c-text-2);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.bar-track{height:10px;border-radius:999px;background:var(--c-panel-soft);overflow:hidden}.bar-fill{display:block;height:100%;min-width:4px;border-radius:999px;background:linear-gradient(90deg,var(--c-brand),var(--c-purple))}.bar-value{font-size:9px;color:var(--c-muted);font-variant-numeric:tabular-nums}.donut-layout{display:flex;align-items:center;justify-content:center;gap:18px;min-height:150px}.donut{width:116px;height:116px;border-radius:50%;position:relative;display:grid;place-items:center;flex:none}.donut:after{content:'';position:absolute;inset:16px;border-radius:50%;background:var(--c-raised)}.donut-center{position:relative;z-index:1;text-align:center}.donut-center b{display:block;font-size:24px}.donut-center span{font-size:8px;color:var(--c-faint)}.donut-legend{display:grid;gap:7px}.donut-legend span{font-size:9px;color:var(--c-muted);display:flex;align-items:center;gap:6px}.donut-legend i{width:8px;height:8px;border-radius:50%;flex:none}.empty-visual{min-height:150px;display:grid;place-items:center;text-align:center;color:var(--c-muted);background:var(--c-panel-soft);border:1px dashed var(--c-line);border-radius:12px;padding:18px}.empty-visual .ui-icon{width:28px;height:28px;margin:0 auto 8px;color:var(--c-faint)}.empty-visual b{font-size:11px}.empty-visual p{font-size:9px;margin-top:4px;color:var(--c-faint)}
.performance-list>article{background:var(--c-raised);border-color:var(--c-line)}.performance-list h3{color:var(--c-text)}.performance-list small{color:var(--c-faint)}.performance-list details{border-color:var(--c-line-soft)}.performance-list summary{color:var(--c-muted)}.performance-list details p{color:var(--c-text-2)}
.report-section{background:linear-gradient(145deg,var(--c-panel),color-mix(in srgb,var(--c-purple) 5%,var(--c-panel)))}.decision-grid{grid-template-columns:repeat(3,1fr)}.decision-grid article{position:relative;display:block;background:var(--c-raised);border:1px solid var(--c-line);padding:16px}.decision-grid article>span{display:grid;width:30px;height:30px;place-items:center;border-radius:10px;background:color-mix(in srgb,var(--c-purple) 11%,var(--c-panel));color:var(--c-purple);margin-bottom:13px}.decision-grid b{font-size:12px;color:var(--c-text)}.decision-grid p{color:var(--c-muted)}.analysis-grid{grid-template-columns:repeat(4,1fr)}.analysis-box{position:relative;background:var(--c-raised);border-color:var(--c-line);border-top:0!important;padding:15px}.analysis-box .analysis-icon{width:32px;height:32px;display:grid;place-items:center;border-radius:10px;margin-bottom:12px}.analysis-box h3{color:var(--c-text);font-size:11px}.analysis-box p{color:var(--c-muted)}.analysis-box.fact .analysis-icon{background:color-mix(in srgb,var(--c-green) 12%,var(--c-panel));color:var(--c-green)}.analysis-box.hypothesis .analysis-icon{background:color-mix(in srgb,var(--c-purple) 12%,var(--c-panel));color:var(--c-purple)}.analysis-box.unknown .analysis-icon{background:color-mix(in srgb,var(--c-amber) 12%,var(--c-panel));color:var(--c-amber)}.analysis-box.next-test .analysis-icon{background:color-mix(in srgb,var(--c-brand) 12%,var(--c-panel));color:var(--c-brand)}
.manual-sync li,.empty-inline,.empty-state{background:var(--c-panel-soft);border-color:var(--c-line)}.manual-copy>b,.empty-state b{color:var(--c-text-2)}.manual-copy small,.empty-state p,.empty-inline{color:var(--c-muted)}
.post-drawer{background:var(--c-panel);color:var(--c-text)}.drawer-close,.drawer-block,.drawer-grid>div{background:var(--c-panel-soft)}.post-drawer>h2{color:var(--c-text)}.drawer-block p,.drawer-grid p{color:var(--c-text-2)}.drawer-block>span,.drawer-grid span{color:var(--c-faint)}
@media(max-width:1320px){.now-grid{grid-template-columns:repeat(3,1fr)}.now-card.primary{grid-column:span 2}.kpi-grid{grid-template-columns:repeat(3,1fr)}}
@media(max-width:1000px){.pipeline-list{grid-template-columns:1fr}.chart-grid{grid-template-columns:1fr}.analysis-grid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:900px){.hero-actions{width:100%}.hero-update{flex:1}.decision-grid{grid-template-columns:1fr}.now-grid{grid-template-columns:1fr 1fr}.now-card.primary{grid-column:span 2}}
@media(max-width:700px){.customer-shell .sidebar:has(.office-back-button){flex-wrap:wrap}.customer-shell .sidebar:has(.office-back-button) .office-back-button{flex:none;margin:0;padding:8px 10px;gap:7px;font-size:10.5px}.customer-shell .sidebar:has(.office-back-button) .sidebar-footer{display:none}}
@media(max-width:640px){.customer-hero{padding:18px;border-radius:18px}.hero-actions{align-items:stretch}.theme-toggle{width:44px;padding:0;justify-content:center}.theme-toggle span{display:none}.now-grid{grid-template-columns:1fr 1fr}.now-card.primary{grid-column:span 2}.now-card{min-height:116px;padding:14px}.now-card .summary-value{font-size:21px}.pipeline-card-meta{grid-template-columns:1fr 1fr}.pipeline-meta:last-child{grid-column:span 2}.kpi-grid{grid-template-columns:1fr 1fr}.chart-grid{grid-template-columns:1fr}.bar-row{grid-template-columns:85px 1fr auto}.donut-layout{gap:12px}.analysis-grid{grid-template-columns:1fr 1fr}.visuals-section{padding:17px}}
@media(max-width:420px){.hero-actions{flex-direction:column}.theme-toggle{width:100%;height:42px}.theme-toggle span{display:inline}.analysis-grid{grid-template-columns:1fr}.pipeline-card-meta{grid-template-columns:1fr}.pipeline-meta:last-child{grid-column:auto}}
@media(prefers-reduced-motion:reduce){.customer-shell *{scroll-behavior:auto!important;transition:none!important}}

/* UX06: customer readability and visual-first hierarchy */
.customer-shell{font-size:15px;line-height:1.55}.customer-shell .main{padding-top:28px;padding-bottom:64px}.customer-dashboard{max-width:1380px}
.customer-hero{padding:30px 32px;margin-bottom:24px}.hero-main h1{font-size:36px;line-height:1.2}.hero-main>p{font-size:16px;line-height:1.6}.account-line{font-size:14px}.status-badge{padding:8px 13px;font-size:13px}.hero-update{min-width:230px;padding:17px 19px}.hero-update span,.hero-update small{font-size:13px}.hero-update b{font-size:15px}.theme-toggle{min-width:106px;padding:0 16px;font-size:13px}.ui-icon{width:22px;height:22px}
.now-grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin-bottom:24px}.now-card{min-height:178px;padding:24px;border-radius:20px}.now-card.primary{grid-column:span 2}.summary-icon{width:48px;height:48px;border-radius:15px}.summary-icon .ui-icon{width:25px;height:25px}.now-card .summary-label{font-size:13px}.now-card .summary-value{font-size:36px;margin:22px 0 8px}.now-card .summary-value.textual{font-size:20px;line-height:1.5}.now-card small{font-size:14px;line-height:1.5}
.workflow-section{display:block;padding:28px 30px;margin-bottom:24px;border-radius:20px}.workflow-copy{width:auto;margin-bottom:24px}.workflow-copy span{font-size:13px}.workflow-copy b{font-size:18px;margin-top:5px}.journey{gap:12px}.journey-step{gap:9px;font-size:14px}.journey-step span{width:42px;height:42px;font-size:14px}.journey-step span em{min-width:20px;height:20px;font-size:10px}.journey i{height:2px}
.section{margin-bottom:24px}.customer-dashboard .page-kicker{font-size:13px}.pipeline-section,.performance-section,.report-section,.manual-sync,.visuals-section{padding:32px;border-radius:20px}.section-header{gap:24px}.section-header h2{font-size:24px;line-height:1.35}.section-lead{font-size:14px;line-height:1.6;margin-top:8px}.card-eyebrow{font-size:13px;margin-bottom:8px}.count-pill,.hypothesis-pill{padding:8px 13px;font-size:13px}
.pipeline-list{grid-template-columns:1fr;gap:14px;margin-top:24px}.pipeline-row{padding:22px;border-radius:17px}.pipeline-topic .topic-name{font-size:18px;line-height:1.45;white-space:normal}.pipeline-topic small,.schedule-cell small{font-size:13px}.detail-button{width:40px;height:40px}.pipeline-card-meta{gap:12px;margin-top:18px}.pipeline-meta{padding:14px}.pipeline-meta>span{font-size:13px;margin-bottom:8px}.pipeline-meta b{font-size:14px}.customer-dashboard .badge,.origin-chip,.measuring{padding:6px 10px;font-size:13px}.actual-metrics{gap:8px}.actual-metric{padding:8px 10px;font-size:14px}.actual-metric b{font-size:13px}.metric-updated{font-size:13px;margin-top:6px}
.manual-sync ul{gap:12px;margin-top:22px}.manual-sync li{gap:12px;padding:18px}.manual-copy>b{font-size:15px}.manual-copy small,.manual-copy summary,.manual-copy details p{font-size:13px}.manual-state{padding:7px 10px;font-size:12px}.empty-inline{padding:20px;font-size:14px}
.kpi-grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin-top:24px}.kpi-card{min-height:190px;padding:22px;border-radius:17px}.kpi-card>span{font-size:14px}.kpi-card strong{font-size:34px;margin:10px 0 5px}.kpi-card small{font-size:13px}.kpi-visual{height:46px;margin-top:20px}.kpi-visual svg{height:46px}.performance-list{grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin-top:20px}.performance-list>article{padding:20px;border-radius:16px}.performance-list h3{font-size:17px;line-height:1.45}.performance-list small,.performance-list summary{font-size:13px}.performance-list details p{font-size:14px;line-height:1.75}
.chart-grid{grid-template-columns:minmax(0,1.45fr) minmax(360px,.8fr);gap:18px;margin-top:24px}.chart-card{padding:24px;border-radius:18px;min-height:330px}.chart-title{margin-bottom:24px}.chart-title .summary-icon{width:44px;height:44px}.chart-title b{font-size:17px}.chart-title small{font-size:13px}.bar-chart{gap:18px}.bar-row{grid-template-columns:minmax(130px,190px) 1fr 70px;gap:14px}.bar-label,.bar-value{font-size:14px}.bar-track{height:18px}.donut-layout{min-height:240px;gap:30px}.donut{width:180px;height:180px}.donut:after{inset:25px}.donut-center b{font-size:36px}.donut-center span{font-size:13px}.donut-legend{gap:12px}.donut-legend span{font-size:14px}.donut-legend i{width:11px;height:11px}.empty-visual{min-height:240px;padding:28px}.empty-visual .ui-icon{width:44px;height:44px}.empty-visual b{font-size:18px}.empty-visual p{font-size:14px;line-height:1.6}
.decision-grid{gap:16px;margin-top:24px}.decision-grid article{padding:22px}.decision-grid article>span{width:44px;height:44px}.decision-grid b{font-size:17px}.decision-grid p{font-size:14px;line-height:1.65}.analysis-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin-top:16px}.analysis-box{padding:22px}.analysis-box .analysis-icon{width:44px;height:44px}.analysis-box h3{font-size:17px}.analysis-box p{font-size:14px;line-height:1.65}.report-cta{margin-top:18px;padding:18px 20px;font-size:15px}.report-cta span{font-size:24px}
.empty-state{padding:48px 24px}.empty-state b{font-size:18px}.empty-state p{font-size:14px;line-height:1.6}.drawer-tags span,.drawer-block>span,.drawer-grid span{font-size:13px}.drawer-block p,.drawer-grid p{font-size:14px}
@media(max-width:1100px){.now-grid,.kpi-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.now-card.primary{grid-column:span 2}.chart-grid{grid-template-columns:1fr}.performance-list{grid-template-columns:1fr}}
@media(max-width:700px){.customer-shell .main{padding-top:12px}.customer-hero{padding:20px}.hero-main h1{font-size:28px}.now-grid{gap:12px}.now-card{min-height:145px;padding:18px}.now-card .summary-value{font-size:30px}.now-card .summary-value.textual{font-size:17px}.workflow-section,.pipeline-section,.performance-section,.report-section,.manual-sync,.visuals-section{padding:20px}.journey{overflow-x:auto;padding:6px 2px 12px;scrollbar-width:none}.journey::-webkit-scrollbar{display:none}.journey-step{flex-direction:column;min-width:58px;font-size:13px}.journey-step b,.journey-step span em{font-size:13px}.kpi-grid{grid-template-columns:1fr}.chart-card{min-height:280px;padding:18px}.bar-row{grid-template-columns:95px 1fr 58px}.bar-label,.bar-value{font-size:13px}.donut{width:150px;height:150px}.donut-layout{min-height:210px}.pipeline-card-meta{grid-template-columns:1fr 1fr}.pipeline-meta:last-child{grid-column:span 2}}
@media(max-width:430px){.now-grid{grid-template-columns:1fr}.now-card.primary{grid-column:auto}.hero-actions{width:100%}.hero-update{min-width:0}.analysis-grid{grid-template-columns:1fr}.donut-layout{flex-direction:column}.pipeline-card-meta{grid-template-columns:1fr}.pipeline-meta:last-child{grid-column:auto}}

/* UX07: spacious global type scale and readable customer navigation */
.customer-shell{font-size:16px;line-height:1.6}.customer-shell .sidebar{padding:22px 18px}.customer-shell .sidebar-header .brand{font-size:17px;line-height:1.45}.customer-shell .sidebar-header .brand-sub{font-size:13px;line-height:1.5}.customer-shell .sidebar-nav{margin-top:18px}.customer-shell .nav-section{gap:7px}.customer-shell .nav-item{min-height:50px;padding:13px 14px;gap:12px;border-radius:13px;font-size:15px;line-height:1.5}.customer-shell .nav-icon-chip{width:24px;height:24px}.customer-shell .nav-icon-chip svg{width:20px;height:20px}.customer-shell .office-back-button{margin:18px 0 6px;padding:14px 15px;font-size:15px}.customer-shell .office-back-button .office-icon{font-size:18px;line-height:1}.customer-shell .sys-status-label{font-size:13px}.customer-shell .sys-status-state{font-size:15px}
.hero-main h1{font-size:40px}.hero-main>p{font-size:17px}.status-badge{font-size:14px}.section-header h2{font-size:27px}.section-lead{font-size:15px}.now-card .summary-label{font-size:14px}.now-card .summary-value{font-size:38px}.now-card .summary-value.textual{font-size:22px}.now-card small{font-size:14px}
.pipeline-list{gap:20px}.pipeline-row{padding:28px}.pipeline-topic .topic-name{font-size:20px}.pipeline-topic small{margin-top:5px;font-size:15px}.pipeline-card-meta{gap:15px;margin-top:22px}.pipeline-meta{padding:17px}.pipeline-meta>span{font-size:14px}.pipeline-meta b,.schedule-cell b{font-size:16px;line-height:1.5}.customer-dashboard .badge,.origin-chip,.measuring{padding:8px 12px;font-size:14px;line-height:1.45}.pipeline-card-metrics{margin-top:16px;padding-top:15px}.actual-metrics{gap:10px}.actual-metric{min-width:88px;padding:10px 13px;font-size:18px;line-height:1.35}.actual-metric b{font-size:13px;margin-bottom:3px}.actual-metric.metric-views,.actual-metric.metric-views-hour,.actual-metric.metric-reaction-rate{min-width:108px;padding:12px 15px;font-size:21px;box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--c-brand) 18%,transparent)}.metric-updated{font-size:14px;margin-top:8px}
.kpi-card>span{font-size:14px}.kpi-card strong{font-size:36px}.kpi-card small{font-size:14px}.performance-list{gap:20px}.performance-list>article{padding:24px}.performance-list h3{font-size:19px}.performance-list small,.performance-list summary{font-size:14px}.decision-grid b,.analysis-box h3,.chart-title b{font-size:18px}.decision-grid p,.analysis-box p,.chart-title small,.bar-label,.bar-value,.donut-legend span{font-size:14px}.drawer-tags span,.drawer-block>span,.drawer-grid span,.drawer-block p,.drawer-grid p{font-size:14px}
@media(max-width:700px){.customer-shell .sidebar{padding:14px 16px}.customer-shell .sidebar-header .brand{font-size:15px}.customer-shell .sidebar:has(.office-back-button){gap:10px}.customer-shell .sidebar:has(.office-back-button) .office-back-button{min-height:44px;margin:0;padding:10px 12px;font-size:14px}.hero-main h1{font-size:32px}.section-header h2{font-size:25px}.pipeline-row{padding:22px}.actual-metric{min-width:82px;font-size:17px}.actual-metric.metric-views,.actual-metric.metric-views-hour,.actual-metric.metric-reaction-rate{min-width:102px;font-size:19px}}
`;

export const customerThemeScript = `
const themeButton=document.getElementById('theme-toggle');
const themeLabel=document.getElementById('theme-label');
const themeMedia=window.matchMedia('(prefers-color-scheme: dark)');
function storedTheme(){try{const value=localStorage.getItem('takumi-customer-theme');return value==='light'||value==='dark'?value:null}catch(_){return null}}
function activeTheme(){return document.documentElement.dataset.customerTheme||(themeMedia.matches?'dark':'light')}
function applyTheme(theme,persist){document.documentElement.dataset.customerTheme=theme;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme==='dark'?'#080d18':'#f4f7fb');if(persist){try{localStorage.setItem('takumi-customer-theme',theme)}catch(_){}}if(themeLabel)themeLabel.textContent=theme==='dark'?'ライト':'ダーク';if(themeButton)themeButton.setAttribute('aria-label',theme==='dark'?'ライトモードに切り替える':'ダークモードに切り替える')}
applyTheme(storedTheme()||(themeMedia.matches?'dark':'light'),false);
themeButton?.addEventListener('click',()=>applyTheme(activeTheme()==='dark'?'light':'dark',true));
themeMedia.addEventListener?.('change',event=>{if(!storedTheme())applyTheme(event.matches?'dark':'light',false)});
`;
