import { Database } from "bun:sqlite";
import { afterAll, describe, expect, test } from "bun:test";
import { createHash, generateKeyPairSync } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { canonicalJson } from "../../web/lib/catfood-harness";
import { CATFOOD_POLICY_SHA256 } from "../../web/lib/catfood-trust";
import { collectCurrentRuntimeSubject, observeTestOnlyRoleLaunch, roleChannelAcceptedSnapshotDigest, type CatfoodEnrollmentRole, type TestEnrollmentBinding } from "../../web/lib/catfood-enrollment";
import { CATFOOD_FINAL_CLOSURE_CHARTER, CATFOOD_SEALED_INPUT_SCHEMA, CATFOOD_SQLITE_EXPORT_PROFILE, type CatfoodGoRootPolicyV1, type CatfoodSealedInputManifestV1 } from "../../web/lib/catfood-final-closure";
import { CatfoodRoleAuthority, buildCustodyReleaseAction, buildEvaluationActionV3, createTestOnlyRoleSession, initializeRoleAuthorityStore, localRoleEvidence, performRoleAction, roleChannelPublicKeyFingerprint, verifyEvaluationJobEnvelope, verifyExpectedEvaluationTargetEnvelope, verifyRoleEvidenceV4, type AuthorityEvaluationJob, type LocalRoleSession, type RoleActionReceiptV2, type RoleChannelBinding, type RoleRunScope } from "../../web/lib/catfood-role-channel";
import { testGoRootPolicy } from "../../tests/catfood-go-root-policy-fixture";
import { CustodyController, CustodyControlError, TestOnlyPreCustodyHost, TestOnlySqliteContinuityWitness, canonicalKeySha256, initializeCustodyController, initializeTestOnlyContinuityWitness, type CanonicalRunKey, type FenceObservation, type RunBinding } from "./controller";

const sha = (value: string | Uint8Array) => createHash("sha256").update(value).digest("hex");
const cj = (value: unknown) => canonicalJson(value as never);
const CLOCK = Date.parse("2026-09-29T12:00:00.000Z");
const key: CanonicalRunKey = { environment_type: "test", deployment_id: "deployment:test", organization_id: "org:test", tenant_id: "tenant:test", account_id: "acct:test", run_id: "run:test" };
const scope: RoleRunScope = { ...key, environment_instance_id: "instance:test", spec_sha256: "1".repeat(64) };
const deferredCleanup = new Set<string>();
afterAll(() => { Bun.gc(true); for (const path of deferredCleanup) rmSync(path, { recursive: true, force: true, maxRetries: 5, retryDelay: 20 }); });

function sealed(profile: CatfoodGoRootPolicyV1["verification_profile"], variant = "a"): CatfoodSealedInputManifestV1 {
  const control = { format: CATFOOD_SQLITE_EXPORT_PROFILE, byte_length: 4096, raw_sha256: variant.repeat(64), logical_schema_sha256: "2".repeat(64) } as const;
  const checkpoint = { ...control, raw_sha256: variant === "a" ? "b".repeat(64) : "c".repeat(64) } as const;
  const body = { schema: CATFOOD_SEALED_INPUT_SCHEMA, charter: CATFOOD_FINAL_CLOSURE_CHARTER, scope, window: { start: "2026-09-29T00:00:00.000Z", end: "2026-09-30T00:00:00.000Z" }, closure: { closed_source_event_id: `event:closed:${variant}`, run_closed_event_id: `event:run:${variant}`, lifecycle: "CLOSED" as const }, journal: { high_water: 42, head_sha256: variant.repeat(64) }, checkpoint: { checkpoint_id: `checkpoint:${variant}`, checkpoint_sha256: variant === "a" ? "4".repeat(64) : "5".repeat(64), pins_sha256: "6".repeat(64) }, retained_source: { archive_sha256: "7".repeat(64), source_digest: "8".repeat(64), producer_identity: "threads:875e75fce20c16c6157b5aa42f759411c52e95fe" }, go: { artifact_sha256: "9".repeat(64), verification_profile_id: profile.profile_id, verification_profile_sha256: sha(cj(profile)), root_fingerprints: profile.keys.map((item) => item.public_key_sha256) }, fixed: { dependencies_sha256: "a".repeat(64), policy_sha256: CATFOOD_POLICY_SHA256, kernel_sha256: "b".repeat(64) }, trust: { environment_provenance_sha256: "c".repeat(64), clock_provenance_sha256: "d".repeat(64), acquisition_provenance_sha256: "e".repeat(64), test_only: true }, expected_bundle_sha256: "f".repeat(64), pair_common_cut_sha256: variant === "a" ? "0".repeat(64) : "1".repeat(64), control, checkpoint_store: checkpoint };
  return { ...body, manifest_id: `manifest:${sha(cj(body)).slice(0, 40)}` } as CatfoodSealedInputManifestV1;
}

function runBinding(manifest: CatfoodSealedInputManifestV1, goRef: unknown): RunBinding {
  return { key, environment_instance_id: scope.environment_instance_id, spec_sha256: scope.spec_sha256, window_sha256: sha(cj(manifest.window)), go_artifact_sha256: manifest.go.artifact_sha256, go_policy_ref_sha256: sha(cj(goRef)), control_store_id: "control:test", checkpoint_store_id: "checkpoint:test", store_pair_lineage_sha256: "3".repeat(64), producer_generation: 1, journal_head_sha256: manifest.journal.head_sha256, checkpoint_head_sha256: manifest.checkpoint.checkpoint_sha256, control_snapshot_sha256: manifest.control.raw_sha256, checkpoint_snapshot_sha256: manifest.checkpoint_store.raw_sha256, pair_common_cut_sha256: manifest.pair_common_cut_sha256, test_only: true };
}

const decode = (session: LocalRoleSession) => JSON.parse(Buffer.from(JSON.parse(String(localRoleEvidence(session).enrollment_envelope_json)).payload, "base64url").toString()) as Record<string, unknown>;

type Fixture = ReturnType<typeof fixture>;
function fixture(activate = true, fenceValid = true) {
  const dir = mkdtempSync(join(tmpdir(), "pre-custody-corrective-")), authorityPath = join(dir, "authority.db"), controllerPath = join(dir, "controller.db"), witnessPath = join(dir, "witness.db");
  for (const path of [authorityPath, controllerPath, witnessPath]) writeFileSync(path, "");
  const authorityKey = generateKeyPairSync("ed25519"), goKey = generateKeyPairSync("ed25519"), authorityPublic = authorityKey.publicKey.export({ type: "spki", format: "pem" }).toString(), goPublic = goKey.publicKey.export({ type: "spki", format: "pem" }).toString();
  const go = testGoRootPolicy({ authority_identity: "fixture-role-authority", authority_public_key_pem: authorityPublic, enrollment_namespace: "fixture:pre-custody", scope, public_keys: [{ key_id: "go:test", public_key_pem: goPublic }], not_before: "2026-09-29T00:00:00.000Z", not_after: "2026-10-03T00:00:00.000Z", acceptance_policy_sha256: CATFOOD_POLICY_SHA256 });
  const roleBinding: RoleChannelBinding = { trust_domain: "TEST_ONLY", issuer: "fixture-role-authority", issuer_key_id: "authority:v4", audience: "ikorabu-catfood", origin: "http://127.0.0.1:32199", credential: "fixture-coarse-service-access-credential", authority_public_key_pem: authorityPublic, enrollment_namespace: "fixture:pre-custody", build_policy_sha256: CATFOOD_POLICY_SHA256, accepted_snapshot_id: "snapshot:pre-custody", accepted_snapshot_sha256: roleChannelAcceptedSnapshotDigest(), policy: { policy_id: "fixture-policy-v1", session_lifetime_ms: 60_000, registration_challenge_lifetime_ms: 5_000, action_challenge_lifetime_ms: 5_000, maximum_outstanding_requests: 64, receipt_retention_ms: 86_400_000, go_root_policy_documents: [go.policy], go_root_workload_selections: [go.selection] } };
  initializeRoleAuthorityStore(authorityPath, roleBinding); initializeCustodyController(controllerPath, "controller:test", roleBinding); initializeTestOnlyContinuityWitness(witnessPath);
  const witness = new TestOnlySqliteContinuityWitness(witnessPath), controller = new CustodyController(controllerPath, witness, roleBinding), manifest = sealed(go.policy.verification_profile), binding = runBinding(manifest, go.ref);
  const fenceAdapter = { inspect({ admitted, binding: current }: any): FenceObservation { return { old_session_id: admitted.session_id, old_process_cannot_execute: fenceValid, old_credentials_revoked: fenceValid, producer_effects_resolved: fenceValid, complete_history_verified: fenceValid, journal_head_sha256: current.journal_head_sha256, checkpoint_head_sha256: current.checkpoint_head_sha256, control_snapshot_sha256: current.control_snapshot_sha256, checkpoint_snapshot_sha256: current.checkpoint_snapshot_sha256, pair_common_cut_sha256: current.pair_common_cut_sha256 }; } };
  const host = new TestOnlyPreCustodyHost({ authority_path: authorityPath, authority_binding: roleBinding, authority_private_key: authorityKey.privateKey, controller, fence_adapter: fenceAdapter, now: () => CLOCK });
  const enrollmentBinding = (role: CatfoodEnrollmentRole, writer?: { key_id: string; key_version: string; public_key_sha256: string; public_key_pem: string }): TestEnrollmentBinding => ({ trust_domain: "TEST_ONLY", issuer: roleBinding.issuer, issuer_key_id: roleBinding.issuer_key_id, audience: roleBinding.audience, origin: roleBinding.origin, credential: roleBinding.credential, public_key_pem: roleBinding.authority_public_key_pem, environment_identity: scope.environment_instance_id, deployment_id: scope.deployment_id, enrollment_namespace: roleBinding.enrollment_namespace, build_policy_sha256: roleBinding.build_policy_sha256, accepted_snapshot_id: roleBinding.accepted_snapshot_id, accepted_snapshot_sha256: roleBinding.accepted_snapshot_sha256, launch_ticket: `launch:${role}`, writer_signing_key_id: writer?.key_id ?? "none", writer_signing_key_version: writer?.key_version ?? "none", writer_signing_public_key_pem: writer?.public_key_pem ?? roleBinding.authority_public_key_pem });
  const rawAuthority = () => new CatfoodRoleAuthority(authorityPath, roleBinding, authorityKey.privateKey, () => CLOCK), rawSessionAuthorities: CatfoodRoleAuthority[] = [];
  const enrollRaw = (role: CatfoodEnrollmentRole, distinct = false) => { const authority = rawAuthority(); rawSessionAuthorities.push(authority); const outer = generateKeyPairSync("ed25519"), outerPem = outer.publicKey.export({ type: "spki", format: "pem" }).toString(), writer = role === "writer" ? { key_id: "writer:raw", key_version: "v1", public_key_sha256: roleChannelPublicKeyFingerprint(outerPem), public_key_pem: outerPem } : undefined, eb = enrollmentBinding(role, writer), base = collectCurrentRuntimeSubject(eb), subject = distinct ? { ...base, pid: base.pid + Math.floor(Math.random() * 100000) + 1, process_start: `${base.process_start}:raw:${Math.random()}` } : base, launch = observeTestOnlyRoleLaunch(eb, role, subject); return createTestOnlyRoleSession(authority, { role, scope, subject, launch, writer_credential: writer, now: () => CLOCK }); };
  const out: any = { dir, authorityPath, controllerPath, witnessPath, authorityKey, roleBinding, go, witness, controller, host, manifest, binding, fenceAdapter, rawAuthority, enrollRaw, close() { for (const authority of rawSessionAuthorities) try { authority.close(); } catch {} try { out.host.close(); } catch {} try { out.witness.close(); } catch {} try { rmSync(dir, { recursive: true, force: true, maxRetries: 5, retryDelay: 20 }); } catch (error) { if (!(error instanceof Error && "code" in error && error.code === "EBUSY")) throw error; deferredCleanup.add(dir); } } };
  host.reserveRun(binding, "reserve:one");
  if (activate) {
    out.custodian = host.admitCustodian({ key, operation_id: "admit:one", lease_expires_ms: CLOCK + 30_000, host_incarnation: "host:one" });
    out.evaluator = host.launchRole(key, "evaluator"); out.writer = host.launchRole(key, "writer"); out.verifier = host.launchRole(key, "verifier");
    out.roleEvidenceSha = sha(cj([out.custodian.evidence, out.evaluator.evidence, out.writer.evidence]));
  }
  return out as Fixture & any;
}

function release(f: Fixture, session = f.custodian.session, manifest = f.manifest, request = "release:canonical", workflow = "instruction:canonical"): RoleActionReceiptV2 {
  return performRoleAction(session, { action: "custodian.evaluation.release", purpose_class: "HISTORICAL_EVIDENCE", request_id: request, logical_target: scope.run_id, body: (actionId) => buildCustodyReleaseAction({ action_id: actionId, manifest, go_root_policy_ref: f.go.ref, evaluator_session_id: String(decode(f.evaluator.session).session_id), writer_session_id: String(decode(f.writer.session).session_id), role_evidence_sha256: f.roleEvidenceSha, workflow_instruction_id: workflow }) });
}
function closeCanonical(f: Fixture) { const receipt = release(f); f.host.closeCustody({ key, manifest: f.manifest, release_receipt: receipt, operation_id: "close:one" }); f.release = receipt; return receipt; }
function issue(f: Fixture, operation = "job:one", options: { lost?: boolean; workflow?: string } = {}) {
  const workflow = options.workflow ?? "instruction:canonical";
  return f.host.issueEvaluationJob({ key, operation_id: operation, evaluator_evidence: f.evaluator.evidence, writer_evidence: f.writer.evidence, role_evidence_sha256: f.roleEvidenceSha, workflow_instruction_id: workflow, workflow_instruction_sha256: sha(workflow), commit_lifetime_ms: 30_000, lose_response_for_test: options.lost });
}
function commit(f: Fixture, job: AuthorityEvaluationJob, verdict: "PASS" | "FAIL" = "PASS") { const evaluator = decode(f.evaluator.session), core = { evaluator: { session_id: evaluator.session_id, build_sha256: "c".repeat(64) }, verdict, reason_codes: verdict === "FAIL" ? ["KNOWN_FAILURE"] : [] }; return performRoleAction(f.evaluator.session, { action: "evaluator.result.commit", purpose_class: "INDEPENDENT_EVALUATION", request_id: job.descriptor.stable_evaluator_request_id, logical_target: job.descriptor.evaluation_job_id, body: () => buildEvaluationActionV3({ job, decision_core: core, evaluator: core.evaluator, source_digest: f.manifest.retained_source.source_digest }) }); }
function target(f: Fixture, job: AuthorityEvaluationJob, operation = "target:one", lost = false) { return f.host.assignExpectedTarget({ key, operation_id: operation, verifier_evidence: f.verifier.evidence, evaluation_job_id: job.descriptor.evaluation_job_id, lose_response_for_test: lost }); }
function nonOwner(f: Fixture) { return f.enrollRaw("custodian"); }
function incidentWithNonOwner(f: Fixture, manifest = f.manifest, operation = "incident:nonowner") { const other = nonOwner(f), receipt = release(f, other, manifest, `${operation}:release`); expect(() => f.host.closeCustody({ key, manifest, release_receipt: receipt, operation_id: operation })).toThrow("NON_ADMITTED_CUSTODIAN"); }
function counts(f: Fixture) { const db = new Database(f.authorityPath, { readonly: true }); try { return { jobs: db.query<{ n: number }, []>("SELECT COUNT(*) n FROM evaluation_jobs").get()!.n, targets: db.query<{ n: number }, []>("SELECT COUNT(*) n FROM expected_evaluation_targets").get()!.n }; } finally { db.close(); } }
function rawCanonicalJob(f: Fixture): AuthorityEvaluationJob { const raw = f.rawAuthority(); try { return raw.issueEvaluationJob({ custody_release_receipt: f.release, manifest: f.manifest, evaluator: verifyRoleEvidenceV4(f.evaluator.evidence, f.roleBinding, "evaluator", scope), writer: verifyRoleEvidenceV4(f.writer.evidence, f.roleBinding, "writer", scope), role_evidence_sha256: f.roleEvidenceSha, workflow_instruction_id: "instruction:canonical", workflow_instruction_sha256: sha("instruction:canonical"), commit_lifetime_ms: 30000 }); } finally { raw.close(); } }
function restartHost(f: Fixture): void { f.host.close(); f.witness.close(); const witness = new TestOnlySqliteContinuityWitness(f.witnessPath), controller = new CustodyController(f.controllerPath, witness, f.roleBinding), host = new TestOnlyPreCustodyHost({ authority_path: f.authorityPath, authority_binding: f.roleBinding, authority_private_key: f.authorityKey.privateKey, controller, fence_adapter: f.fenceAdapter, now: () => CLOCK }); f.witness = witness; f.controller = controller; f.host = host; }

describe("N01-N18 corrected", () => {
  test("N01 canonical admission pins authenticated custodian lineage", () => { const f = fixture(); try { expect(f.controller.state(key)).toMatchObject({ state: "ACTIVE", admitted: { session_id: decode(f.custodian.session).session_id }, binding: { control_store_id: "control:test" } }); } finally { f.close(); } });
  test("N02 two OS processes overlap on one SQLite admission and only one wins", async () => { const f = fixture(false); try { const bindingPath = join(f.dir, "authority-binding.json"), keyPath = join(f.dir, "key.json"), gate = join(f.dir, "go"), worker = join(import.meta.dir, "admission-race-worker.ts"); writeFileSync(bindingPath, JSON.stringify(f.roleBinding)); writeFileSync(keyPath, JSON.stringify(key)); const launch = (suffix: string) => { const candidatePath = join(f.dir, `candidate-${suffix}.json`); writeFileSync(candidatePath, JSON.stringify({ subject_sha256: suffix.repeat(64), launch_id: `launch:${suffix}`, action_key_fingerprint: (suffix === "a" ? "a" : "b").repeat(64), process_id: `process:${suffix}`, host_incarnation: `host:${suffix}`, build_sha256: "c".repeat(64) })); return Bun.spawn([process.execPath, worker, f.controllerPath, f.witnessPath, bindingPath, keyPath, candidatePath, gate, `admit:${suffix}`], { stdout: "pipe", stderr: "pipe" }); }; const a = launch("a"), b = launch("b"); writeFileSync(gate, "go"); const [ac, bc, ao, bo] = await Promise.all([a.exited, b.exited, new Response(a.stdout).text(), new Response(b.stdout).text()]); expect([ac, bc].filter((code) => code === 0)).toHaveLength(1); expect(`${ao}${bo}`).toContain("ADMITTED"); expect(f.controller.state(key).state).toBe("ADMITTING"); } finally { f.close(); } });
  test("N03 immutable run binding rejects namespace/store/GO changes", () => { const f = fixture(); try { expect(() => f.host.reserveRun({ ...f.binding, control_store_id: "control:fork" }, "reserve:fork")).toThrow("RUN_BINDING_CONFLICT"); } finally { f.close(); } });
  test("N04 lease is evaluated and self-asserted fencing cannot replace", () => { const f = fixture(true, false); try { expect(() => f.host.observeLeaseAndReplace({ key, observed_now_ms: CLOCK + 40_000, operation_id: "replace:bad", lease_expires_ms: CLOCK + 90_000, host_incarnation: "host:two" })).toThrow("REPLACEMENT_NOT_PROVEN"); expect(f.controller.state(key).state).toBe("RECOVERY_REQUIRED"); } finally { f.close(); } });
  test("N05 trusted host fencing adapter permits continuity-preserving successor", () => { const f = fixture(); try { const next = f.host.observeLeaseAndReplace({ key, observed_now_ms: CLOCK + 40_000, operation_id: "replace:good", lease_expires_ms: CLOCK + 90_000, host_incarnation: "host:two" }); expect(f.controller.state(key)).toMatchObject({ state: "ACTIVE", admitted: { session_id: decode(next.session).session_id } }); } finally { f.close(); } });
  test("N06 close and applied job operation replay are exact and idempotent", () => { const f = fixture(); try { const receipt = closeCanonical(f); expect(f.host.closeCustody({ key, manifest: f.manifest, release_receipt: receipt, operation_id: "ignored:exact-replay" }).replay).toBeTrue(); const first = issue(f); expect(issue(f).descriptor.evaluation_job_id).toBe(first.descriptor.evaluation_job_id); expect(counts(f).jobs).toBe(1); } finally { f.close(); } });
  test("N07 authentic non-owner history cannot become canonical", () => { const f = fixture(); try { incidentWithNonOwner(f, sealed(f.go.policy.verification_profile, "b")); expect(f.controller.state(key).state).toBe("INCIDENT"); } finally { f.close(); } });
  test("N08 PASS/PASS labels cannot select a non-owner history", () => { const f = fixture(); try { incidentWithNonOwner(f); expect(counts(f).jobs).toBe(0); } finally { f.close(); } });
  test("N09 actual manifest store/head/W mismatch fails closed", () => { const f = fixture(); try { const changed = sealed(f.go.policy.verification_profile, "b"), receipt = release(f, f.custodian.session, changed, "release:mismatch"); expect(() => f.host.closeCustody({ key, manifest: changed, release_receipt: receipt, operation_id: "close:mismatch" })).toThrow("CUSTODY_LINEAGE_MISMATCH"); expect(f.controller.state(key).state).toBe("INCIDENT"); } finally { f.close(); } });
  test("N10 authority rollback below pinned high-water is detected", () => { const f = fixture(); try { closeCanonical(f); issue(f); const db = new Database(f.authorityPath); db.query("UPDATE role_authority_continuity SET revision=revision-1").run(); db.close(); expect(() => f.host.launchRole(key, "observer")).toThrow("AUTHORITY_ROLLBACK"); } finally { f.close(); } });
  test("N11 witness lost response is recovered only under same operation id", () => { const f = fixture(false); try { const otherKey = { ...key, run_id: "run:witness" }, otherBinding = { ...f.binding, key: otherKey }; f.witness.setFailureForTest("AFTER_COMMIT"); expect(() => f.host.reserveRun(otherBinding, "reserve:lost")).toThrow("WITNESS_RESPONSE_LOST"); f.witness.setFailureForTest("NONE"); expect(f.host.reserveRun(otherBinding, "reserve:lost")).toMatchObject({ state: "RESERVED" }); } finally { f.close(); } });
  test("N12 incident revokes a previously current target", () => { const f = fixture(); try { closeCanonical(f); const job = issue(f); commit(f, job); const current = target(f, job); expect(f.host.publicationEligibility(key, current).current).toBeTrue(); incidentWithNonOwner(f); expect(() => f.host.publicationEligibility(key, current)).toThrow(); } finally { f.close(); } });
  test("N13 lost responses recover the exact original job and target", () => { const f = fixture(); try { closeCanonical(f); expect(() => issue(f, "job:lost", { lost: true })).toThrow("TEST_ONLY_RESPONSE_LOST"); const job = f.host.reconcileEvaluationJob(key, "job:lost"); commit(f, job); expect(() => target(f, job, "target:lost", true)).toThrow("TEST_ONLY_RESPONSE_LOST"); const envelope = f.host.reconcileExpectedTarget(key, "target:lost"); expect(f.host.publicationEligibility(key, envelope).current).toBeTrue(); expect(counts(f)).toEqual({ jobs: 1, targets: 1 }); } finally { f.close(); } });
  test("N14 unresolved producer/fence evidence blocks replacement", () => { const f = fixture(true, false); try { expect(() => f.host.observeLeaseAndReplace({ key, observed_now_ms: CLOCK + 40_000, operation_id: "replace:unresolved", lease_expires_ms: CLOCK + 90_000, host_incarnation: "host:two" })).toThrow(); } finally { f.close(); } });
  test("N15 ordinary host exposes no raw authority/controller capability", () => { const f = fixture(); try { expect(Object.getOwnPropertyNames(f.host)).toEqual([]); expect((f.host as any).authority).toBeUndefined(); expect((f.host as any).controller).toBeUndefined(); } finally { f.close(); } });
  test("N16 foreign scope and unauthenticated claims cannot establish custody", () => { const f = fixture(); try { const foreign = { ...f.manifest, scope: { ...f.manifest.scope, account_id: "acct:foreign" } } as any; expect(() => f.host.closeCustody({ key, manifest: foreign, release_receipt: release(f), operation_id: "close:foreign" })).toThrow(); } finally { f.close(); } });
  test("N17 fixed safety commands cannot create positive authority", () => { const f = fixture(); try { const before = counts(f); expect(() => f.host.safety(key, { kind: "RUN", effect: () => issue(f) } as any)).toThrow("SAFETY_COMMAND_INVALID"); expect(f.host.safety(key, { kind: "STATUS_READ" })).toMatchObject({ state: "ACTIVE" }); expect(counts(f)).toEqual(before); } finally { f.close(); } });
  test("N18 adjunct is TEST_ONLY and canonical Git-blob integrity is explicit", () => { const f = fixture(); try { expect(() => f.host.reserveRun({ ...f.binding, key: { ...key, run_id: "run:prod" }, test_only: false } as any, "reserve:prod")).toThrow("RUN_BINDING_INVALID"); const integrity = JSON.parse(readFileSync(join(import.meta.dir, "integrity.json"), "utf8")) as { files: { path: string; canonical_lf_sha256: string; git_blob_sha1: string }[] }; for (const entry of integrity.files) { const canonical = readFileSync(join(import.meta.dir, entry.path), "utf8").replaceAll("\r\n", "\n"), blob = createHash("sha1").update(`blob ${Buffer.byteLength(canonical)}\0${canonical}`).digest("hex"); expect(sha(canonical)).toBe(entry.canonical_lf_sha256); expect(blob).toBe(entry.git_blob_sha1); } } finally { f.close(); } });
});

describe("C01-C25 hostile regressions", () => {
  test("C01 non-admitted authentic custodian cannot close", () => { const f = fixture(); try { incidentWithNonOwner(f); } finally { f.close(); } });
  test("C02 B presents PASS first but cannot become canonical", () => { const f = fixture(); try { incidentWithNonOwner(f); expect(f.controller.state(key).canonical_manifest_sha256).toBeNull(); } finally { f.close(); } });
  test("C03 admitted A FAIL versus non-admitted B PASS cannot shop PASS", () => { const f = fixture(); try { incidentWithNonOwner(f); expect(counts(f).jobs).toBe(0); } finally { f.close(); } });
  test("C04 admitted A PASS and non-admitted B PASS still rejects B", () => { const f = fixture(); try { closeCanonical(f); issue(f); incidentWithNonOwner(f); expect(f.controller.state(key).state).toBe("INCIDENT"); } finally { f.close(); } });
  test("C05 release receipt session must equal admitted session", () => { const f = fixture(); try { incidentWithNonOwner(f); } finally { f.close(); } });
  test("C06 manifest control/checkpoint/journal heads must match pinned lineage", () => { const f = fixture(); try { const changed = sealed(f.go.policy.verification_profile, "b"); expect(() => f.host.closeCustody({ key, manifest: changed, release_receipt: release(f, f.custodian.session, changed), operation_id: "close:heads" })).toThrow("CUSTODY_LINEAGE_MISMATCH"); } finally { f.close(); } });
  test("C07 W must match pinned window", () => { const f = fixture(); try { const changed = { ...f.manifest, window: { ...f.manifest.window, end: "2026-10-01T00:00:00.000Z" } } as any; expect(() => f.host.closeCustody({ key, manifest: changed, release_receipt: release(f, f.custodian.session, changed), operation_id: "close:w" })).toThrow(); } finally { f.close(); } });
  test("C08 attacker authority binding is not an accepted caller parameter", () => { const f = fixture(); try { closeCanonical(f); const forged = { ...f.evaluator.evidence, enrollment_envelope_json: "{}" }; expect(() => (f.host.issueEvaluationJob as any)({ key, operation_id: "job:attacker", evaluator_evidence: forged, writer_evidence: f.writer.evidence, role_evidence_sha256: f.roleEvidenceSha, workflow_instruction_id: "instruction:canonical", workflow_instruction_sha256: sha("instruction:canonical"), commit_lifetime_ms: 30000, binding: { authority_public_key_pem: "attacker" } })).toThrow(); } finally { f.close(); } });
  test("C09 forged job/target and attacker binding cannot enter reconciliation", () => { const f = fixture(); try { closeCanonical(f); expect(() => issue(f, "job:lost", { lost: true })).toThrow(); const result = (f.host.reconcileEvaluationJob as any)(key, "job:lost", { descriptor: { verdict: "PASS" } }, { attacker: true }); expect(result.descriptor.authority_incarnation).toBeTruthy(); } finally { f.close(); } });
  test("C10 alternate authentic job cannot replace pending original", () => { const f = fixture(); try { closeCanonical(f); expect(() => issue(f, "job:lost", { lost: true })).toThrow(); const alternateReceipt = release(f, f.custodian.session, f.manifest, "release:alternate-job", "instruction:alternate"), raw = f.rawAuthority(); try { raw.issueEvaluationJob({ custody_release_receipt: alternateReceipt, manifest: f.manifest, evaluator: verifyRoleEvidenceV4(f.evaluator.evidence, f.roleBinding, "evaluator", scope), writer: verifyRoleEvidenceV4(f.writer.evidence, f.roleBinding, "writer", scope), role_evidence_sha256: f.roleEvidenceSha, workflow_instruction_id: "instruction:alternate", workflow_instruction_sha256: sha("alternate"), commit_lifetime_ms: 30000 }); } finally { raw.close(); } expect(() => f.host.reconcileEvaluationJob(key, "job:lost")).toThrow("UNGUARDED_AUTHORITY_EFFECT"); expect(f.controller.state(key).state).toBe("INCIDENT"); } finally { f.close(); } });
  test("C11 alternate authentic target cannot replace pending original", () => { const f = fixture(); try { closeCanonical(f); const job = issue(f); commit(f, job); expect(() => target(f, job, "target:lost", true)).toThrow(); const raw = f.rawAuthority(); try { raw.assignExpectedEvaluationTarget({ verifier: verifyRoleEvidenceV4(f.verifier.evidence, f.roleBinding, "verifier", scope), evaluation_job_id: job.descriptor.evaluation_job_id, purpose: "VERIFY_EXPECTED" }); } finally { raw.close(); } expect(() => f.host.reconcileExpectedTarget(key, "target:lost")).toThrow("UNGUARDED_AUTHORITY_EFFECT"); expect(f.controller.state(key).state).toBe("INCIDENT"); } finally { f.close(); } });
  test("C12 lost job response blocks a new operation id", () => { const f = fixture(); try { closeCanonical(f); expect(() => issue(f, "job:lost", { lost: true })).toThrow(); expect(() => issue(f, "job:new")).toThrow("CONTINUITY_OPERATION_PENDING"); } finally { f.close(); } });
  test("C13 lost target response blocks a new operation id", () => { const f = fixture(); try { closeCanonical(f); const job = issue(f); commit(f, job); expect(() => target(f, job, "target:lost", true)).toThrow(); expect(() => target(f, job, "target:new")).toThrow("CONTINUITY_OPERATION_PENDING"); } finally { f.close(); } });
  test("C14 raw authority bypass is detected by ordinary host boundary", () => { const f = fixture(); try { closeCanonical(f); const raw = f.rawAuthority(); try { raw.issueEvaluationJob({ custody_release_receipt: f.release, manifest: f.manifest, evaluator: verifyRoleEvidenceV4(f.evaluator.evidence, f.roleBinding, "evaluator", scope), writer: verifyRoleEvidenceV4(f.writer.evidence, f.roleBinding, "writer", scope), role_evidence_sha256: f.roleEvidenceSha, workflow_instruction_id: "instruction:canonical", workflow_instruction_sha256: sha("raw"), commit_lifetime_ms: 30000 }); } finally { raw.close(); } expect(() => f.host.launchRole(key, "observer")).toThrow("UNGUARDED_AUTHORITY_EFFECT"); expect(f.controller.state(key).state).toBe("INCIDENT"); } finally { f.close(); } });
  test("C15 safety closure cannot issue job", () => { const f = fixture(); try { expect(() => f.host.safety(key, { kind: "STOP", run: () => issue(f) } as any)).toThrow("SAFETY_COMMAND_INVALID"); expect(counts(f).jobs).toBe(0); } finally { f.close(); } });
  test("C16 safety closure cannot assign target", () => { const f = fixture(); try { expect(() => f.host.safety(key, { kind: "RECONCILE", run: () => "target" } as any)).toThrow("SAFETY_COMMAND_INVALID"); expect(counts(f).targets).toBe(0); } finally { f.close(); } });
  test("C17 rollback revision reuse with different authenticated job is detected", () => { const f = fixture(); try { closeCanonical(f); const first = issue(f), revision = first.descriptor.authority_revision; const db = new Database(f.authorityPath); db.query("DELETE FROM evaluation_jobs WHERE evaluation_job_id=?").run(first.descriptor.evaluation_job_id); db.query("UPDATE role_authority_continuity SET revision=?").run(revision - 1); db.close(); const replacementReceipt = release(f, f.custodian.session, f.manifest, "release:replacement", "instruction:replacement"), raw = f.rawAuthority(); try { raw.issueEvaluationJob({ custody_release_receipt: replacementReceipt, manifest: f.manifest, evaluator: verifyRoleEvidenceV4(f.evaluator.evidence, f.roleBinding, "evaluator", scope), writer: verifyRoleEvidenceV4(f.writer.evidence, f.roleBinding, "writer", scope), role_evidence_sha256: f.roleEvidenceSha, workflow_instruction_id: "instruction:replacement", workflow_instruction_sha256: sha("replacement"), commit_lifetime_ms: 30000 }); } finally { raw.close(); } expect(() => f.host.launchRole(key, "observer")).toThrow("AUTHORITY_REVISION_REUSED"); } finally { f.close(); } });
  test("C18 authority incarnation mismatch is detected", () => { const f = fixture(); try { const db = new Database(f.authorityPath); db.query("UPDATE role_authority_continuity SET incarnation='authority:replaced'").run(); db.close(); expect(() => f.host.launchRole(key, "observer")).toThrow("AUTHORITY_INCARNATION_MISMATCH"); } finally { f.close(); } });
  test("C19 concurrent incident cannot be overwritten by job completion", () => { const f = fixture(); try { closeCanonical(f); expect(() => issue(f, "job:race", { lost: true })).toThrow(); incidentWithNonOwner(f); expect(() => f.host.reconcileEvaluationJob(key, "job:race")).toThrow("INCIDENT_TERMINAL"); expect(f.controller.state(key).state).toBe("INCIDENT"); } finally { f.close(); } });
  test("C20 concurrent incident cannot be overwritten by target completion", () => { const f = fixture(); try { closeCanonical(f); const job = issue(f); commit(f, job); expect(() => target(f, job, "target:race", true)).toThrow(); incidentWithNonOwner(f); expect(() => f.host.reconcileExpectedTarget(key, "target:race")).toThrow("INCIDENT_TERMINAL"); expect(f.controller.state(key).state).toBe("INCIDENT"); } finally { f.close(); } });
  test("C21 old CURRENT target cannot publish after incident", () => { const f = fixture(); try { closeCanonical(f); const job = issue(f); commit(f, job); const envelope = target(f, job); incidentWithNonOwner(f); expect(() => f.host.publicationEligibility(key, envelope)).toThrow(); } finally { f.close(); } });
  test("C22 operation id reused across kinds is rejected", () => { const f = fixture(); try { closeCanonical(f); const job = issue(f, "shared:op"); commit(f, job); expect(() => target(f, job, "shared:op")).toThrow("OPERATION_DOMAIN_CONFLICT"); } finally { f.close(); } });
  test("C23 operation id reused across K is rejected", () => { const f = fixture(); try { closeCanonical(f); issue(f, "shared:key"); expect(() => f.controller.appliedEffect({ ...key, run_id: "run:other" }, "shared:key", "ISSUE_JOB")).toThrow("OPERATION_DOMAIN_CONFLICT"); } finally { f.close(); } });
  test("C24 witness/controller rollback-domain limitation is explicit", () => { const text = readFileSync(join(import.meta.dir, "README.md"), "utf8"); expect(text).toContain("TEST_ONLY witness protocol mechanism"); expect(text).toContain("same rollback domain"); expect(text).toContain("REAL_DEPLOYMENT_CLOSURE_NOT_VERIFIED"); });
  test("C25 CRLF checkout conversion does not alter canonical Git-blob identity", () => { const lf = "alpha\nbeta\n", crlf = lf.replaceAll("\n", "\r\n"), gitBlob = (text: string) => createHash("sha1").update(`blob ${Buffer.byteLength(text)}\0${text}`).digest("hex"); expect(gitBlob(crlf.replaceAll("\r\n", "\n"))).toBe(gitBlob(lf)); expect(sha(crlf)).not.toBe(sha(lf)); });
});

describe("R01-R07 corrective02 pending exact identity", () => {
  test("R01 pending lost job rejects same-revision authentic rollback replacement", () => { const f = fixture(); try { closeCanonical(f); expect(() => issue(f, "r01:job", { lost: true })).toThrow("TEST_ONLY_RESPONSE_LOST"); const db = new Database(f.authorityPath), firstRow = db.query<{ descriptor_envelope: string }, []>("SELECT descriptor_envelope FROM evaluation_jobs").get()!, original = verifyEvaluationJobEnvelope(firstRow.descriptor_envelope, f.roleBinding), revision = original.descriptor.authority_revision; db.query("DELETE FROM evaluation_jobs").run(); db.query("UPDATE role_authority_continuity SET revision=? WHERE singleton=1").run(revision - 1); db.close(); const replacement = rawCanonicalJob(f); expect(replacement.descriptor.authority_revision).toBe(revision); expect(replacement.descriptor.evaluation_job_id).not.toBe(original.descriptor.evaluation_job_id); expect(() => f.host.reconcileEvaluationJob(key, "r01:job")).toThrow("AUTHORITY_REVISION_REUSED"); expect(f.controller.state(key)).toMatchObject({ state: "INCIDENT", incident_count: 1 }); } finally { f.close(); } });
  test("R02 pending lost target rejects same-revision authentic rollback replacement", () => { const f = fixture(); try { closeCanonical(f); const job = issue(f); commit(f, job); expect(() => target(f, job, "r02:target", true)).toThrow("TEST_ONLY_RESPONSE_LOST"); const db = new Database(f.authorityPath), firstEnvelope = db.query<{ target_envelope: string }, []>("SELECT target_envelope FROM expected_evaluation_targets").get()!.target_envelope, original = verifyExpectedEvaluationTargetEnvelope(firstEnvelope, f.roleBinding), revision = original.target_revision; db.query("DELETE FROM expected_evaluation_targets").run(); db.query("UPDATE role_authority_continuity SET revision=? WHERE singleton=1").run(revision - 1); db.close(); const raw = f.rawAuthority(); let replacement: string; try { replacement = raw.assignExpectedEvaluationTarget({ verifier: verifyRoleEvidenceV4(f.verifier.evidence, f.roleBinding, "verifier", scope), evaluation_job_id: job.descriptor.evaluation_job_id, purpose: "VERIFY_EXPECTED" }); } finally { raw.close(); } const replacementTarget = verifyExpectedEvaluationTargetEnvelope(replacement, f.roleBinding); expect(replacementTarget.target_revision).toBe(revision); expect(replacementTarget.assignment_id).not.toBe(original.assignment_id); expect(() => f.host.reconcileExpectedTarget(key, "r02:target")).toThrow("AUTHORITY_REVISION_REUSED"); expect(f.controller.state(key)).toMatchObject({ state: "INCIDENT", incident_count: 1 }); } finally { f.close(); } });
  test("R03 exact job and target survive host restart without volatile lost-response maps", () => { const jobFixture = fixture(); try { closeCanonical(jobFixture); expect(() => issue(jobFixture, "r03:job", { lost: true })).toThrow("TEST_ONLY_RESPONSE_LOST"); const db = new Database(jobFixture.authorityPath, { readonly: true }), expectedId = verifyEvaluationJobEnvelope(db.query<{ descriptor_envelope: string }, []>("SELECT descriptor_envelope FROM evaluation_jobs").get()!.descriptor_envelope, jobFixture.roleBinding).descriptor.evaluation_job_id; db.close(); restartHost(jobFixture); expect(jobFixture.host.reconcileEvaluationJob(key, "r03:job").descriptor.evaluation_job_id).toBe(expectedId); } finally { jobFixture.close(); } const targetFixture = fixture(); try { closeCanonical(targetFixture); const job = issue(targetFixture); commit(targetFixture, job); expect(() => target(targetFixture, job, "r03:target", true)).toThrow("TEST_ONLY_RESPONSE_LOST"); const db = new Database(targetFixture.authorityPath, { readonly: true }), expectedEnvelope = db.query<{ target_envelope: string }, []>("SELECT target_envelope FROM expected_evaluation_targets").get()!.target_envelope; db.close(); restartHost(targetFixture); const envelope = targetFixture.host.reconcileExpectedTarget(key, "r03:target"); expect(envelope).toBe(expectedEnvelope); expect(targetFixture.host.publicationEligibility(key, envelope).current).toBeTrue(); } finally { targetFixture.close(); } });
  test("R04 pending effect disappearance without replacement creates durable incident", () => { const f = fixture(); try { closeCanonical(f); expect(() => issue(f, "r04:job", { lost: true })).toThrow("TEST_ONLY_RESPONSE_LOST"); const db = new Database(f.authorityPath); db.query("DELETE FROM evaluation_jobs").run(); db.close(); expect(() => f.host.reconcileEvaluationJob(key, "r04:job")).toThrow("AUTHORITY_EFFECT_DISAPPEARED"); expect(f.controller.state(key)).toMatchObject({ state: "INCIDENT", incident_count: 1 }); expect(() => f.host.reconcileEvaluationJob(key, "r04:job")).toThrow(); expect(f.controller.state(key).state).toBe("INCIDENT"); } finally { f.close(); } });
  test("R05 delayed exact completion and retry cannot erase rollback incident", () => { const f = fixture(); try { closeCanonical(f); expect(() => issue(f, "r05:job", { lost: true })).toThrow("TEST_ONLY_RESPONSE_LOST"); const db = new Database(f.authorityPath), firstRow = db.query<{ descriptor_envelope: string }, []>("SELECT descriptor_envelope FROM evaluation_jobs").get()!, original = verifyEvaluationJobEnvelope(firstRow.descriptor_envelope, f.roleBinding), revision = original.descriptor.authority_revision; db.query("DELETE FROM evaluation_jobs").run(); db.query("UPDATE role_authority_continuity SET revision=? WHERE singleton=1").run(revision - 1); db.close(); rawCanonicalJob(f); expect(() => f.host.reconcileEvaluationJob(key, "r05:job")).toThrow("AUTHORITY_REVISION_REUSED"); expect(() => f.controller.completeJobEffect(key, "r05:job", original)).toThrow("INCIDENT_TERMINAL"); expect(f.controller.state(key).state).toBe("INCIDENT"); expect(() => f.host.reconcileEvaluationJob(key, "r05:job")).toThrow(); expect(f.controller.state(key).state).toBe("INCIDENT"); } finally { f.close(); } });
  test("R06 pinned ACKNOWLEDGED job and target reconcile after crash-window restart", () => { const jobFixture = fixture(); try { closeCanonical(jobFixture); const db = new Database(jobFixture.authorityPath, { readonly: true }), continuity = db.query<{ incarnation: string; revision: number }, []>("SELECT incarnation,revision FROM role_authority_continuity WHERE singleton=1").get()!; db.close(); jobFixture.controller.beginJobEffect(key, "r06:job", { authority_incarnation: continuity.incarnation, authority_revision: continuity.revision + 1, workflow_instruction_id: "instruction:canonical", release_receipt_sha256: jobFixture.release.receipt_sha256 }); const job = rawCanonicalJob(jobFixture); jobFixture.controller.pinJobEffectIdentity(key, "r06:job", job); restartHost(jobFixture); expect(jobFixture.host.reconcileEvaluationJob(key, "r06:job").descriptor.evaluation_job_id).toBe(job.descriptor.evaluation_job_id); } finally { jobFixture.close(); } const targetFixture = fixture(); try { closeCanonical(targetFixture); const job = issue(targetFixture); commit(targetFixture, job); const db = new Database(targetFixture.authorityPath, { readonly: true }), continuity = db.query<{ incarnation: string; revision: number }, []>("SELECT incarnation,revision FROM role_authority_continuity WHERE singleton=1").get()!; db.close(); targetFixture.controller.beginTargetEffect(key, "r06:target", { authority_incarnation: continuity.incarnation, authority_revision: continuity.revision + 1, evaluation_job_id: job.descriptor.evaluation_job_id, verifier_session_id: String(decode(targetFixture.verifier.session).session_id) }); const raw = targetFixture.rawAuthority(); let envelope: string; try { envelope = raw.assignExpectedEvaluationTarget({ verifier: verifyRoleEvidenceV4(targetFixture.verifier.evidence, targetFixture.roleBinding, "verifier", scope), evaluation_job_id: job.descriptor.evaluation_job_id, purpose: "VERIFY_EXPECTED" }); } finally { raw.close(); } targetFixture.controller.pinTargetEffectIdentity(key, "r06:target", envelope); restartHost(targetFixture); expect(targetFixture.host.reconcileExpectedTarget(key, "r06:target")).toBe(envelope); } finally { targetFixture.close(); } });
  test("R07 same-revision alternate effect cannot coexist with exact pending job or target", () => { const jobFixture = fixture(); try { closeCanonical(jobFixture); expect(() => issue(jobFixture, "r07:job", { lost: true })).toThrow("TEST_ONLY_RESPONSE_LOST"); const db = new Database(jobFixture.authorityPath), revision = db.query<{ revision: number }, []>("SELECT revision FROM role_authority_continuity WHERE singleton=1").get()!.revision; db.query("UPDATE role_authority_continuity SET revision=? WHERE singleton=1").run(revision - 1); db.close(); const alternateReceipt = release(jobFixture, jobFixture.custodian.session, jobFixture.manifest, "release:r07:alternate", "instruction:r07:alternate"), raw = jobFixture.rawAuthority(); try { raw.issueEvaluationJob({ custody_release_receipt: alternateReceipt, manifest: jobFixture.manifest, evaluator: verifyRoleEvidenceV4(jobFixture.evaluator.evidence, jobFixture.roleBinding, "evaluator", scope), writer: verifyRoleEvidenceV4(jobFixture.writer.evidence, jobFixture.roleBinding, "writer", scope), role_evidence_sha256: jobFixture.roleEvidenceSha, workflow_instruction_id: "instruction:r07:alternate", workflow_instruction_sha256: sha("instruction:r07:alternate"), commit_lifetime_ms: 30000 }); } finally { raw.close(); } expect(() => jobFixture.host.reconcileEvaluationJob(key, "r07:job")).toThrow("AUTHORITY_REVISION_REUSED"); expect(jobFixture.controller.state(key).state).toBe("INCIDENT"); } finally { jobFixture.close(); } const targetFixture = fixture(); try { closeCanonical(targetFixture); const job = issue(targetFixture); commit(targetFixture, job); expect(() => target(targetFixture, job, "r07:target", true)).toThrow("TEST_ONLY_RESPONSE_LOST"); const db = new Database(targetFixture.authorityPath), revision = db.query<{ revision: number }, []>("SELECT revision FROM role_authority_continuity WHERE singleton=1").get()!.revision; db.query("UPDATE role_authority_continuity SET revision=? WHERE singleton=1").run(revision - 1); db.close(); const raw = targetFixture.rawAuthority(); try { raw.assignExpectedEvaluationTarget({ verifier: verifyRoleEvidenceV4(targetFixture.verifier.evidence, targetFixture.roleBinding, "verifier", scope), evaluation_job_id: job.descriptor.evaluation_job_id, purpose: "VERIFY_EXPECTED" }); } finally { raw.close(); } expect(() => targetFixture.host.reconcileExpectedTarget(key, "r07:target")).toThrow("AUTHORITY_REVISION_REUSED"); expect(targetFixture.controller.state(key).state).toBe("INCIDENT"); } finally { targetFixture.close(); } });
});

describe("P1-P7 independent audit attack reproduction", () => {
  test("P1/H19 non-admitted canonical takeover is rejected", () => { const f = fixture(); try { incidentWithNonOwner(f); } finally { f.close(); } });
  test("P2/H15 raw authority path is detected and quarantined", () => { const f = fixture(); try { closeCanonical(f); const raw = f.rawAuthority(); try { raw.issueEvaluationJob({ custody_release_receipt: f.release, manifest: f.manifest, evaluator: verifyRoleEvidenceV4(f.evaluator.evidence, f.roleBinding, "evaluator", scope), writer: verifyRoleEvidenceV4(f.writer.evidence, f.roleBinding, "writer", scope), role_evidence_sha256: f.roleEvidenceSha, workflow_instruction_id: "instruction:canonical", workflow_instruction_sha256: sha("p2"), commit_lifetime_ms: 30000 }); } finally { raw.close(); } expect(() => f.host.publicationEligibility(key, "forged")).toThrow("UNGUARDED_AUTHORITY_EFFECT"); } finally { f.close(); } });
  test("P3/P3b caller substitution and trust injection have no route", () => { const f = fixture(); try { closeCanonical(f); expect(() => issue(f, "job:lost", { lost: true })).toThrow(); const exact = (f.host.reconcileEvaluationJob as any)(key, "job:lost", { attacker: true }, { binding: "attacker" }); expect(exact.descriptor.workflow_instruction_id).toBe("instruction:canonical"); } finally { f.close(); } });
  test("P4 authority rollback is terminal", () => { const f = fixture(); try { closeCanonical(f); issue(f); const db = new Database(f.authorityPath); db.query("UPDATE role_authority_continuity SET revision=1").run(); db.close(); expect(() => f.host.launchRole(key, "observer")).toThrow("AUTHORITY_ROLLBACK"); } finally { f.close(); } });
  test("P5 mismatched replacement/store/head/W cannot close", () => { const f = fixture(); try { const changed = sealed(f.go.policy.verification_profile, "b"); expect(() => f.host.closeCustody({ key, manifest: changed, release_receipt: release(f, f.custodian.session, changed), operation_id: "p5" })).toThrow("CUSTODY_LINEAGE_MISMATCH"); } finally { f.close(); } });
  test("P6 incident cannot be overwritten back to CLOSED", () => { const f = fixture(); try { closeCanonical(f); expect(() => issue(f, "p6:job", { lost: true })).toThrow(); incidentWithNonOwner(f); expect(() => f.host.reconcileEvaluationJob(key, "p6:job")).toThrow("INCIDENT_TERMINAL"); expect(f.controller.state(key).state).toBe("INCIDENT"); } finally { f.close(); } });
  test("P7 arbitrary safety positive effect is rejected", () => { const f = fixture(); try { expect(() => f.host.safety(key, { kind: "RECONCILE", callback: () => issue(f) } as any)).toThrow("SAFETY_COMMAND_INVALID"); expect(counts(f)).toEqual({ jobs: 0, targets: 0 }); } finally { f.close(); } });
});
